import type { Metadata } from "next";
import StaticInfoPage from "@/components/StaticInfoPage";
import { englishLanguageAlternates } from "@/lib/localization";

export const metadata: Metadata = {
  title: { absolute: "Privacy Policy | FourFeetz Studios" },
  description: "Learn how FourFeetz Studios collects, uses, and protects contact information, customer photos, analytics data, and cookies.",
  alternates: englishLanguageAlternates("/privacy", "/ko/privacy"),
};

export default function PrivacyPage() {
  return <StaticInfoPage eyebrow="Policy" title="Privacy Policy" description="This policy explains how FourFeetz Studios handles information when you visit the website or contact the studio." updated="September 21, 2026" sections={[
    { title: "Information We Collect", paragraphs: ["We may receive information you choose to provide, such as your name, email address, organization, and message when you contact us. Basic technical information may also be collected by hosting, security, and analytics services to operate and protect the website."] },
    { title: "How We Use Information", items: ["Respond to inquiries and communicate about requested services.", "Operate, secure, maintain, and improve the website.", "Understand aggregate website usage and content performance.", "Meet legal obligations and prevent misuse or fraud."] },
    { title: "Cookies & Service Providers", paragraphs: ["The site uses Google Analytics to measure page visits and interactions. Google Analytics may use cookies and online identifiers and receive information such as browser and device details and referral sources. These data should not be assumed to be completely anonymous. Hosting and embedded media providers may also process technical information when their services are accessed.", <span key="google-privacy">Read <a className="font-bold underline" href="https://policies.google.com/technologies/partner-sites">how Google uses information from sites that use its services</a>. You can manage cookies in your browser and use the <a className="font-bold underline" href="https://tools.google.com/dlpage/gaoptout">Google Analytics opt-out browser add-on</a>.</span>] },
    { title: "Google Advertising", paragraphs: ["The site is preparing for Google AdSense; advertising is not activated by this policy page. If Google ads are enabled, third-party vendors, including Google, may use cookies to serve ads based on your previous visits to this and other websites. Google's advertising cookies allow Google and its partners to personalize ads based on those visits. Before advertising is enabled, FourFeetz must review the consent requirements that apply to actual visitor regions and the selected advertising settings.", <span key="ad-choices">You can manage or disable personalized advertising in <a className="font-bold underline" href="https://myadcenter.google.com/">Google My Ad Center</a>, or manage participating third-party advertising cookies through <a className="font-bold underline" href="https://optout.aboutads.info/">YourAdChoices</a>. Disabling personalization does not necessarily remove ads.</span>] },
    { title: "Customer Photos & Production Materials", paragraphs: ["Pet photos, stories, and wording supplied by a customer are used to review the inquiry and complete the agreed production.", "FourFeetz will seek separate permission before publishing customer photos or finished work in its portfolio or promotional materials. Project-specific retention and deletion terms should be agreed before production begins."] },
    { title: "Affiliate & Referral Links", paragraphs: ["Some pages on FourFeetz may include affiliate or referral links to products and services that are genuinely used in our production workflow.", "If a visitor registers or purchases through these links, FourFeetz may receive a commission, referral reward, or promotional credit at no additional cost to the visitor.", "These relationships never influence our editorial opinions or recommendations."] },
    { title: "International Privacy Rights", paragraphs: ["If you are located in the European Economic Area (EEA), the United Kingdom, Switzerland, or other regions with applicable privacy laws, you may have additional rights regarding access, correction, deletion, or restriction of your personal information."] },
    { title: "Retention & Your Choices", paragraphs: ["FourFeetz does not currently apply one fixed retention period to every inquiry and production file. We retain personal information only as long as reasonably necessary for the purpose it was collected, legal obligations, or dispute resolution. Project-specific retention and deletion terms should be confirmed before production. You may request access, correction, or deletion by contacting fourfeetzstudio@gmail.com, subject to applicable law."] },
    { title: "Operator Information", paragraphs: ["Business name: FourFeetz (포피츠) · Representative: Minsik Park · Business registration number: 865-16-02920 · Email: fourfeetzstudio@gmail.com"] },
    { title: "Policy Updates", paragraphs: ["We may update this policy as the website and studio services evolve. The date above identifies the latest revision. Continued use of the website after an update means the revised policy applies from its effective date."] },
  ]} cta={{ eyebrow: "Privacy Questions", title: "Need clarification about your information?", description: "Contact the studio for privacy requests or questions about this policy.", href: "/contact", label: "Contact Us" }} />;
}
