import Image from "next/image";
import Link from "next/link";
import type { CharacterDetail } from "@/lib/characterDetails";
import { characterDetails } from "@/lib/characterDetails";

function Heading({ eyebrow, title }: { eyebrow: string; title: string }) {
  return <div><p className="text-sm font-black uppercase tracking-[0.35em] text-[#a67c52]">{eyebrow}</p><h2 className="mt-3 text-4xl font-black tracking-tight text-[#2b2119] md:text-6xl">{title}</h2></div>;
}

export default function CharacterDetailPage({ character }: { character: CharacterDetail }) {
  const related = characterDetails.filter((item) => item.slug !== character.slug).slice(0, 3);
  const image = `/images/characters/${character.slug}/portrait.png`;
  const schema = { "@context": "https://schema.org", "@type": "Person", name: character.name, description: character.tagline, image, url: `https://fourfeetz.com/characters/${character.slug}` };
  return <main>
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} />
    <section className="mx-auto grid max-w-7xl gap-10 px-6 py-16 md:grid-cols-[0.92fr_0.88fr] md:items-center md:py-20">
      <div><p className="text-sm font-black uppercase tracking-[0.35em] text-[#a67c52]">Original Character</p><h1 className="mt-4 text-5xl font-black tracking-tight text-[#2b2119] md:text-7xl">{character.name}</h1><p className="mt-4 text-2xl font-black text-[#6f4e37]">{character.species}</p><p className="mt-6 max-w-2xl text-lg leading-8 text-[#76685d]">{character.tagline}</p></div>
      <div className="relative mx-auto aspect-[4/3] w-full max-w-[560px] overflow-hidden rounded-[32px] border border-[#eadfce] bg-white shadow-xl shadow-[#6f4e37]/10"><Image src={image} alt={`${character.name} official studio portrait`} fill priority sizes="(min-width: 768px) 560px, 100vw" className="object-contain p-5" /></div>
    </section>
    <section className="border-y border-[#eadfce] bg-white px-6 py-20"><div className="mx-auto grid max-w-7xl gap-10 md:grid-cols-[0.42fr_0.58fr]"><Heading eyebrow="Character Story" title="Meet the Character" /><div className="space-y-6 text-lg leading-8 text-[#76685d]"><p>{character.story}</p><p><strong className="text-[#2b2119]">Role in the FourFeetz universe.</strong> {character.role}</p></div></div></section>
    <section className="px-6 py-20"><div className="mx-auto max-w-7xl"><Heading eyebrow="Profile" title="Personality & Abilities" /><div className="mt-8 grid gap-5 md:grid-cols-3">{character.personality.map((item) => <article key={item} className="rounded-3xl border border-[#eadfce] bg-white p-6 shadow-sm"><h3 className="text-2xl font-black text-[#2b2119]">{item}</h3><p className="mt-3 leading-7 text-[#76685d]">A defining trait that guides {character.name}&apos;s choices, expressions, and relationships.</p></article>)}</div><div className="mt-5 grid gap-5 md:grid-cols-2"><article className="rounded-3xl border border-[#eadfce] bg-white p-7"><h3 className="text-2xl font-black text-[#2b2119]">Favorite Things</h3><ul className="mt-4 space-y-2 text-[#76685d]">{character.favorites.map(item => <li key={item}>- {item}</li>)}</ul></article><article className="rounded-3xl border border-[#eadfce] bg-white p-7"><h3 className="text-2xl font-black text-[#2b2119]">Abilities</h3><ul className="mt-4 space-y-2 text-[#76685d]">{character.abilities.map(item => <li key={item}>- {item}</li>)}</ul></article></div></div></section>
    <section className="border-y border-[#eadfce] bg-white px-6 py-20"><div className="mx-auto max-w-7xl"><Heading eyebrow="Appearance" title="Visual Identity" /><p className="mt-6 max-w-3xl text-lg leading-8 text-[#76685d]">{character.appearance}</p><div className="mt-8 flex gap-4">{character.colors.map(color => <div key={color} className="h-20 flex-1 rounded-2xl border border-[#eadfce] shadow-sm" style={{ backgroundColor: color }}><span className="sr-only">Color {color}</span></div>)}</div></div></section>
    <section className="px-6 py-20"><div className="mx-auto max-w-7xl"><Heading eyebrow="Production" title="Production & Prompt Notes" /><div className="mt-8 grid gap-5 md:grid-cols-2"><article className="rounded-3xl border border-[#eadfce] bg-white p-7 shadow-sm"><h3 className="text-2xl font-black text-[#2b2119]">Production Notes</h3><p className="mt-4 leading-8 text-[#76685d]">{character.productionNotes}</p></article><article className="rounded-3xl border border-[#eadfce] bg-[#2b2119] p-7 shadow-xl"><h3 className="text-2xl font-black text-white">Prompt Notes</h3><p className="mt-4 leading-8 text-[#eadfce]">{character.promptNotes}</p></article></div></div></section>
    <section className="border-y border-[#eadfce] bg-white px-6 py-20"><div className="mx-auto max-w-7xl"><Heading eyebrow="Gallery" title="Studio Portrait Studies" /><div className="mt-8 grid gap-5 md:grid-cols-3">{character.gallery.map((study) => <figure key={study.label} className="overflow-hidden rounded-3xl border border-[#eadfce] bg-[#fffaf4] p-4"><div className="relative aspect-square overflow-hidden rounded-2xl bg-white"><Image src={study.image} alt={`${character.name} ${study.label}`} fill sizes="(min-width: 768px) 30vw, 100vw" className={study.fit === "cover" ? "object-cover" : "object-contain p-3"} /></div><figcaption className="pt-4 text-sm font-bold text-[#6f4e37]">{study.label}</figcaption></figure>)}</div></div></section>
    <section className="px-6 py-20"><div className="mx-auto max-w-7xl"><Heading eyebrow="Future Stories" title="What Comes Next" /><p className="mt-6 max-w-3xl text-lg leading-8 text-[#76685d]">{character.futureStories}</p><div className="mt-10 grid gap-5 md:grid-cols-3">{related.map(item => <Link key={item.slug} href={`/characters/${item.slug}`} className="rounded-3xl border border-[#eadfce] bg-white p-6 shadow-sm transition hover:-translate-y-1 hover:shadow-xl"><p className="text-sm font-black uppercase tracking-[0.2em] text-[#a67c52]">{item.species}</p><h3 className="mt-3 text-3xl font-black text-[#2b2119]">{item.name}</h3><p className="mt-3 text-[#76685d]">{item.tagline}</p></Link>)}</div></div></section>
    <section className="px-6 pb-24"><div className="mx-auto flex max-w-7xl flex-col gap-6 rounded-[40px] bg-[#6f4e37] p-8 text-white shadow-xl md:flex-row md:items-center md:justify-between md:p-12"><div><p className="text-sm font-black uppercase tracking-[0.3em] text-[#e5c9a8]">FourFeetz Universe</p><h2 className="mt-3 text-4xl font-black">See the characters in motion.</h2></div><Link href="/works/haru-first-journey" className="w-fit rounded-full bg-white px-7 py-4 font-black text-[#6f4e37]">Explore the featured film</Link></div></section>
  </main>;
}
