"use client";

import Image from "next/image";
import Link from "next/link";
import { Search, X } from "lucide-react";
import { usePathname, useRouter, useSearchParams } from "next/navigation";
import { useEffect, useMemo, useState } from "react";
import HeroIllustrationCard from "./HeroIllustrationCard";

type InsightArticle = { category: string; title: string; desc: string; readTime: string; href: string; image: string; tags: string[]; keywords: string[] };

const howHaruImage = "/images/insights/premium/how-haru-hero.png";
const featuredInsight = { category: "Behind the Scenes", title: "How HARU Was Created", desc: "The official production story behind HARU: visual identity, character drift, reference sheets, first-shot images, motion, and continuity review.", meta: "24 min read", date: "July 2026", href: "/insights/how-haru-was-created", image: howHaruImage };

const categories = ["All", "AI Video", "AI Music", "Tools", "Prompts", "Characters", "Design", "Workflow", "Images", "Filmmaking", "Behind the Scenes", "Social Media"];

const articles: InsightArticle[] = [
  { category: "Behind the Scenes", title: "How HARU Was Created", desc: "The official FourFeetz production story covering visual identity, failed tests, character drift, first-shot images, AI animation, and continuity review.", readTime: "24 min read", href: "/insights/how-haru-was-created", image: howHaruImage, tags: ["Characters", "Workflow", "Behind the Scenes"], keywords: ["HARU", "AI character consistency", "character drift", "first-shot image", "Google Flow", "Runway", "Kling AI"] },
  { category: "Workflow", title: "Google Flow Complete Guide", desc: "A production-tested guide to references, scene planning, camera language, lighting, consistency and multi-shot filmmaking with HARU.", readTime: "28 min read", href: "/insights/google-flow-complete-guide", image: "/images/insights/production/google-flow-studio-haru.png", tags: ["AI Video", "Workflow", "Filmmaking", "Prompts"], keywords: ["Google Flow", "Veo", "camera", "lighting", "HARU", "scene planning"] },
  { category: "AI Video", title: "Runway Gen-4.5 Complete Review", desc: "An independent creator review based on real HARU motion tests, character consistency, camera control, speed and production cost.", readTime: "19 min read", href: "/insights/runway-gen45-review", image: "/images/insights/production/runway-gen45-set-hugo.png", tags: ["AI Video", "Tools", "Filmmaking"], keywords: ["Runway", "Gen-4.5", "motion", "camera", "HARU", "review"] },
  { category: "AI Video", title: "Kling AI Complete Review", desc: "A practical FourFeetz review of Continue, End Frame, Extend, character consistency and targeted video repair using HARU scenes.", readTime: "18 min read", href: "/insights/kling-ai-complete-review", image: "/images/insights/production/kling-ai-storyboard-luna.png", tags: ["AI Video", "Tools", "Workflow"], keywords: ["Kling AI", "Continue", "End Frame", "Extend", "video repair", "HARU"] },
  { category: "Images", title: "Flux Image Guide", desc: "How FourFeetz prepares stronger HARU references, first frames, lighting studies and thumbnail foundations without exposing master prompts.", readTime: "15 min read", href: "/insights/flux-image-guide", image: "/images/insights/production/flux-image-design-oli.png", tags: ["Images", "Prompts", "Characters"], keywords: ["Flux", "reference image", "first frame", "HARU"] },
  { category: "Filmmaking", title: "AI Lighting Guide", desc: "Production notes on golden hour, soft interiors, cloudy daylight, night scenes and maintaining believable light across HARU shots.", readTime: "14 min read", href: "/insights/ai-lighting-guide", image: "/images/insights/production/ai-lighting-test-milo.png", tags: ["Filmmaking", "Prompts", "Design"], keywords: ["lighting", "golden hour", "cinematic", "HARU"] },
  { category: "Filmmaking", title: "Camera Movement Guide", desc: "A practical camera-language guide built from HARU tracking, push-in, reveal, orbit and static-scene tests.", readTime: "14 min read", href: "/insights/camera-movement-guide", image: "/images/insights/production/camera-movement-hugo.png", tags: ["Filmmaking", "AI Video", "Prompts"], keywords: ["camera movement", "tracking", "push in", "HARU"] },
  { category: "Design", title: "AI Thumbnail Design Guide", desc: "The FourFeetz approach to readable character thumbnails, emotional framing, contrast and mobile-first review.", readTime: "13 min read", href: "/insights/ai-thumbnail-design-guide", image: "/images/insights/ai-thumbnail-design-guide.png", tags: ["Design", "Images", "Characters"], keywords: ["thumbnail", "composition", "HARU", "YouTube"] },
  { category: "Workflow", title: "AI Storyboarding Guide", desc: "How we plan HARU's position, screen direction, lens intention, continuity and edit rhythm before generation.", readTime: "16 min read", href: "/insights/ai-storyboarding-guide", image: "/images/insights/production/ai-storyboarding-haru-pori.png", tags: ["Workflow", "Filmmaking", "Design"], keywords: ["storyboard", "shot list", "continuity", "HARU"] },
  { category: "Characters", title: "Character Consistency Guide", desc: "Reference discipline, identity checks and scene-to-scene review methods used to keep HARU recognizable.", readTime: "17 min read", href: "/insights/character-consistency-guide", image: "/images/insights/production/character-consistency-family.png", tags: ["Characters", "Images", "Workflow", "Prompts"], keywords: ["character consistency", "HARU", "reference sheet"] },
  { category: "AI Music", title: "Best AI Music Tools for Video", desc: "A creator-focused comparison based on building HARU themes, background cues and long-form atmosphere.", readTime: "15 min read", href: "/insights/best-ai-music-tools", image: "/images/insights/production/ai-music-pori.png", tags: ["AI Music", "Tools", "Workflow"], keywords: ["Suno", "soundtrack", "HARU", "music"] },
  { category: "Workflow", title: "A Repeatable AI Video Workflow", desc: "The public beginner-to-intermediate version of the FourFeetz pipeline from idea and references to review, edit and delivery.", readTime: "18 min read", href: "/insights/repeatable-ai-video-workflow", image: "/images/insights/ai-video-workflow.png", tags: ["Workflow", "AI Video", "Filmmaking"], keywords: ["production workflow", "HARU", "editing", "publishing"] },
  { category: "Prompts", title: "Writing Better Image-to-Video Prompts", desc: "A safe public framework for subject action, camera motion, environment and lighting based on HARU tests.", readTime: "15 min read", href: "/insights/image-to-video-prompts", image: "/images/insights/production/image-to-video-haru-luna.png", tags: ["Prompts", "AI Video", "Filmmaking"], keywords: ["image to video", "prompt", "camera", "HARU"] },
  { category: "Social Media", title: "Reframing 16:9 AI Films for Vertical Video", desc: "How HARU First Journey became a vertical cut while protecting subject placement, motion and mobile readability.", readTime: "14 min read", href: "/insights/reframing-16-9-guide", image: "/images/insights/reframing-16-9-guide.png", tags: ["Social Media", "Workflow", "Design"], keywords: ["vertical video", "Shorts", "Reels", "TikTok", "HARU"] },
  { category: "Tools", title: "Kling vs Veo", desc: "A scene-by-scene planning comparison focused on motion realism, prompt control, continuity and production speed.", readTime: "12 min read", href: "/insights/kling-vs-veo", image: "/images/insights/kling-vs-veo.png", tags: ["Tools", "AI Video"], keywords: ["Kling", "Veo", "comparison"] },
];

const guides = articles.slice(0, 6);
const slugifyTag = (value: string) => value.toLowerCase().replace(/\s+/g, "-");
const normalize = (value: string) => value.trim().toLowerCase();

function Thumbnail({ src, alt }: { src: string; alt: string }) { return <div className="relative aspect-video overflow-hidden rounded-t-2xl bg-[#f6ebdd]"><Image src={src} alt={alt} fill sizes="(min-width:1280px)30vw,(min-width:768px)45vw,100vw" className="object-cover transition-transform duration-200 group-hover:scale-[1.02]" /></div>; }

export default function InsightsHub() {
  const router = useRouter();
  const pathname = usePathname();
  const searchParams = useSearchParams();
  const requestedTag = searchParams.get("tag") ?? "all";
  const requestedQuery = searchParams.get("q") ?? "";
  const [activeTag, setActiveTag] = useState(requestedTag);
  const [query, setQuery] = useState(requestedQuery);

  useEffect(() => { setActiveTag(requestedTag); setQuery(requestedQuery); }, [requestedTag, requestedQuery]);

  function updateUrl(nextTag: string, nextQuery: string) {
    const params = new URLSearchParams(searchParams.toString());
    nextTag === "all" ? params.delete("tag") : params.set("tag", nextTag);
    nextQuery.trim() ? params.set("q", nextQuery.trim()) : params.delete("q");
    const next = params.toString();
    router.push(next ? `${pathname}?${next}` : pathname, { scroll: false });
  }

  const filtered = useMemo(() => articles.filter((article) => {
    const tagMatch = activeTag === "all" || [article.category, ...article.tags].some((tag) => slugifyTag(tag) === activeTag);
    const haystack = normalize([article.title, article.desc, article.category, ...article.tags, ...article.keywords].join(" "));
    return tagMatch && (!normalize(query) || haystack.includes(normalize(query)));
  }), [activeTag, query]);

  return <main>
    <section className="mx-auto grid max-w-7xl gap-10 px-6 py-16 md:grid-cols-[0.92fr_0.88fr] md:items-center md:py-20"><div><p className="text-sm font-black uppercase tracking-[0.35em] text-[#a67c52]">CREATOR KNOWLEDGE HUB</p><h1 className="mt-4 text-5xl font-black leading-tight tracking-tight text-[#2b2119] md:text-7xl">Insights</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-[#76685d]">Production-tested guides, honest tool reviews, HARU case studies and practical workflows from FourFeetz Studios.</p></div><HeroIllustrationCard src="/images/insights-hero-v2.png" alt="Editorial research tools for FourFeetz creative knowledge" priority /></section>

    <section className="border-y border-[#eadfce] bg-white px-6 py-16 md:py-20"><Link href={featuredInsight.href} className="mx-auto grid max-w-7xl gap-8 rounded-[40px] border border-[#eadfce] bg-[#fffdf8] p-8 shadow-xl shadow-[#6f4e37]/10 transition duration-200 hover:-translate-y-[3px] hover:shadow-2xl focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#6f4e37] md:grid-cols-[minmax(0,3fr)_minmax(260px,2fr)] md:items-center md:p-10 lg:gap-10 lg:p-12"><div><p className="text-sm font-black uppercase tracking-[0.22em] text-[#a67c52]">{featuredInsight.category}</p><h2 className="mt-4 max-w-4xl text-4xl font-black text-[#2b2119] md:text-5xl">{featuredInsight.title}</h2><p className="mt-5 max-w-3xl text-lg leading-8 text-[#76685d]">{featuredInsight.desc}</p><p className="mt-6 text-sm font-bold text-[#9a8775]">{featuredInsight.meta} · {featuredInsight.date}</p><span className="mt-8 inline-flex rounded-full bg-[#6f4e37] px-7 py-4 font-black text-white">Read Article</span></div><div className="relative aspect-[16/10] overflow-hidden rounded-[28px] border border-[#d8c3ad] bg-[#f2e8dc] shadow-lg shadow-[#6f4e37]/10 md:h-full md:min-h-[260px] md:max-h-[320px] md:aspect-auto"><Image src={featuredInsight.image} alt="HARU in the FourFeetz AI animation studio surrounded by character references, camera and editing tools" fill sizes="(min-width:1280px)36vw,(min-width:768px)40vw,100vw" className="object-cover" style={{ objectPosition: "50% 48%" }} /></div></Link></section>

    <section className="px-6 py-12"><div className="mx-auto max-w-7xl"><div className="relative max-w-2xl"><Search className="pointer-events-none absolute left-5 top-1/2 h-5 w-5 -translate-y-1/2 text-[#a67c52]" aria-hidden="true" /><input value={query} onChange={(e)=>{setQuery(e.target.value);updateUrl(activeTag,e.target.value);}} placeholder="Search titles, summaries, tags, tools and HARU workflows" aria-label="Search Insights" className="w-full rounded-full border border-[#d8c3ad] bg-white py-4 pl-14 pr-12 text-[#2b2119] shadow-sm outline-none transition focus:border-[#6f4e37] focus:ring-2 focus:ring-[#a67c52]/30" />{query ? <button type="button" onClick={()=>{setQuery("");updateUrl(activeTag,"");}} aria-label="Clear search" className="absolute right-4 top-1/2 -translate-y-1/2 rounded-full p-2 text-[#6f4e37] hover:bg-[#f2e8dc]"><X className="h-4 w-4" /></button> : null}</div><div className="mt-6 flex flex-wrap gap-2">{categories.map((category)=>{const slug=slugifyTag(category);const active=activeTag===slug;return <button key={category} type="button" aria-pressed={active} onClick={()=>{setActiveTag(slug);updateUrl(slug,query);}} className={`rounded-full border px-4 py-2 text-xs font-black uppercase tracking-[0.16em] transition focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#a67c52] ${active ? "border-[#6f4e37] bg-[#6f4e37] text-white" : "border-[#d8c3ad] bg-white text-[#6f4e37] hover:border-[#6f4e37]"}`}>{category}</button>})}</div></div></section>

    <section className="px-6 pb-20"><div className="mx-auto flex max-w-7xl items-end justify-between gap-6"><div><p className="text-sm font-black uppercase tracking-[0.35em] text-[#a67c52]">Knowledge Library</p><h2 className="mt-3 text-4xl font-black text-[#2b2119] md:text-6xl">{filtered.length} {filtered.length===1?"Article":"Articles"}</h2></div>{activeTag!=="all"||query?<button type="button" onClick={()=>{setActiveTag("all");setQuery("");updateUrl("all","");}} className="text-sm font-black text-[#6f4e37]">Reset filters</button>:null}</div>{filtered.length?<div className="mx-auto mt-8 grid max-w-7xl gap-5 md:grid-cols-2 xl:grid-cols-3">{filtered.map((article)=><Link key={article.href} href={article.href} className="group flex h-full flex-col rounded-3xl border border-[#eadfce] bg-white p-5 shadow-sm transition duration-200 hover:-translate-y-[3px] hover:shadow-lg focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#6f4e37]"><Thumbnail src={article.image} alt={`${article.title} thumbnail`} /><div className="flex flex-1 flex-col pt-5"><p className="text-sm font-black text-[#a67c52]">{article.category}</p><h3 className="mt-3 text-2xl font-black leading-tight text-[#2b2119]">{article.title}</h3><p className="mt-3 flex-1 leading-7 text-[#76685d]">{article.desc}</p><div className="mt-5 flex flex-wrap gap-2">{article.tags.slice(0,3).map(tag=><span key={tag} className="rounded-full bg-[#f2e8dc] px-3 py-1 text-[11px] font-black uppercase tracking-[0.12em] text-[#6f4e37]">{tag}</span>)}</div><div className="mt-6 flex items-center justify-between text-sm font-bold"><span className="text-[#9a8775]">{article.readTime}</span><span className="text-[#6f4e37]">Read Article →</span></div></div></Link>)}</div>:<div className="mx-auto mt-8 max-w-7xl rounded-[32px] border border-[#eadfce] bg-white p-10 text-center"><h3 className="text-2xl font-black text-[#2b2119]">No matching articles</h3><p className="mt-3 text-[#76685d]">Try a broader search or choose another tag.</p></div>}</section>

    <section className="border-y border-[#eadfce] bg-white px-6 py-20"><div className="mx-auto max-w-7xl"><p className="text-sm font-black uppercase tracking-[0.35em] text-[#a67c52]">Evergreen</p><h2 className="mt-3 text-4xl font-black text-[#2b2119] md:text-6xl">Popular Guides</h2><div className="mt-8 grid gap-4 md:grid-cols-3 xl:grid-cols-6">{guides.map((guide)=><Link key={guide.href} href={guide.href} className="rounded-3xl border border-[#eadfce] bg-[#fffdf8] p-6 shadow-sm transition hover:-translate-y-[3px] hover:shadow-lg focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#6f4e37]"><h3 className="text-xl font-black text-[#2b2119]">{guide.title}</h3><p className="mt-4 text-xs font-black uppercase tracking-[0.18em] text-[#a67c52]">Open Guide</p></Link>)}</div></div></section>
  </main>;
}
