import Image from "next/image";
import Link from "next/link";
import type { ResourceDetail } from "@/lib/resourceDetails";
import { resourceDetails } from "@/lib/resourceDetails";

function Heading({ eyebrow, title }: { eyebrow: string; title: string }) { return <div><p className="text-sm font-black uppercase tracking-[0.35em] text-[#a67c52]">{eyebrow}</p><h2 className="mt-3 text-4xl font-black tracking-tight text-[#2b2119] md:text-6xl">{title}</h2></div>; }

export default function ResourceDetailPage({ resource }: { resource: ResourceDetail }) {
  const related = resourceDetails.filter(item => item.slug !== resource.slug).slice(0, 3);
  const download = `/downloads/${resource.slug}.md`;
  const heroImage = `/images/resources/${resource.slug}-detail.png`;
  const schema = { "@context": "https://schema.org", "@type": "CreativeWork", name: resource.title, description: resource.description, url: `https://fourfeetz.com/resources/${resource.slug}`, isAccessibleForFree: true };
  return <main>
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} />
    <section className="mx-auto grid max-w-7xl gap-10 px-6 py-16 md:grid-cols-[0.92fr_0.88fr] md:items-center md:py-20"><div><p className="text-sm font-black uppercase tracking-[0.35em] text-[#a67c52]">{resource.category}</p><h1 className="mt-4 text-5xl font-black leading-tight tracking-tight text-[#2b2119] md:text-7xl">{resource.title}</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-[#76685d]">{resource.description}</p></div><div className="relative aspect-[4/3] overflow-hidden rounded-[32px] border border-[#eadfce] bg-white shadow-xl shadow-[#6f4e37]/10"><Image src={heroImage} alt={`${resource.title} preview`} fill priority sizes="(min-width: 768px) 560px, 100vw" className="object-contain p-5" /></div></section>
    <section className="border-y border-[#eadfce] bg-white px-6 py-20"><div className="mx-auto grid max-w-7xl gap-10 md:grid-cols-[0.42fr_0.58fr]"><Heading eyebrow="Overview" title="Built for Repeatable Work" /><p className="text-lg leading-8 text-[#76685d]">{resource.overview}</p></div></section>
    <section className="px-6 py-20"><div className="mx-auto max-w-7xl"><Heading eyebrow="Preview" title="What Is Included" /><div className="mt-8 grid gap-5 md:grid-cols-2">{resource.preview.map((item, index) => <article key={item} className="rounded-3xl border border-[#eadfce] bg-white p-7 shadow-sm"><p className="text-sm font-black text-[#a67c52]">{String(index + 1).padStart(2, "0")}</p><h3 className="mt-3 text-2xl font-black text-[#2b2119]">{item}</h3></article>)}</div></div></section>
    <section className="border-y border-[#eadfce] bg-white px-6 py-20"><div className="mx-auto max-w-7xl"><Heading eyebrow="Download" title="Add It to Your Workflow" /><div className="mt-8 rounded-[32px] border border-[#eadfce] bg-[#fffdf8] p-8 shadow-sm md:flex md:items-center md:justify-between"><div><h3 className="text-2xl font-black text-[#2b2119]">FourFeetz Studio Edition</h3><p className="mt-3 text-[#76685d]">Markdown format, easy to adapt for Notion, Docs, or your production repository.</p></div><a href={download} download className="mt-6 inline-flex rounded-full bg-[#6f4e37] px-7 py-4 font-black text-white md:mt-0">Download Free Resource</a></div></div></section>
    <section className="px-6 py-20"><div className="mx-auto max-w-7xl"><Heading eyebrow="How to Use" title="A Practical Process" /><ol className="mt-8 grid gap-5 md:grid-cols-2">{resource.howTo.map((item, index) => <li key={item} className="rounded-3xl border border-[#eadfce] bg-white p-7"><span className="font-black text-[#a67c52]">Step {index + 1}</span><p className="mt-3 text-lg leading-8 text-[#2b2119]">{item}</p></li>)}</ol></div></section>
    <section className="border-y border-[#eadfce] bg-white px-6 py-20"><div className="mx-auto max-w-7xl"><Heading eyebrow="Best Practices" title="Use It Well" /><div className="mt-8 grid gap-5 md:grid-cols-2">{resource.bestPractices.map(item => <article key={item} className="rounded-3xl border border-[#eadfce] bg-[#fffdf8] p-6 font-bold leading-7 text-[#2b2119]">{item}</article>)}</div></div></section>
    <section className="px-6 py-20"><div className="mx-auto max-w-4xl"><Heading eyebrow="FAQ" title="Questions, Answered" /><div className="mt-8 space-y-4">{resource.faq.map(item => <details key={item.question} className="rounded-3xl border border-[#eadfce] bg-white p-6"><summary className="cursor-pointer text-xl font-black text-[#2b2119]">{item.question}</summary><p className="mt-4 leading-8 text-[#76685d]">{item.answer}</p></details>)}</div></div></section>
    <section className="border-t border-[#eadfce] bg-white px-6 py-20"><div className="mx-auto max-w-7xl"><Heading eyebrow="Related Resources" title="Continue Building" /><div className="mt-8 grid gap-5 md:grid-cols-3">{related.map(item => <Link key={item.slug} href={`/resources/${item.slug}`} className="rounded-3xl border border-[#eadfce] bg-[#fffdf8] p-7 shadow-sm transition hover:-translate-y-1 hover:shadow-xl"><p className="text-sm font-black text-[#a67c52]">{item.category}</p><h3 className="mt-3 text-2xl font-black text-[#2b2119]">{item.title}</h3><p className="mt-3 leading-7 text-[#76685d]">{item.description}</p></Link>)}</div></div></section>
    <section className="px-6 pb-24"><div className="mx-auto flex max-w-7xl flex-col gap-6 rounded-[40px] bg-[#6f4e37] p-8 text-white md:flex-row md:items-center md:justify-between md:p-12"><div><p className="text-sm font-black uppercase tracking-[0.3em] text-[#e5c9a8]">FourFeetz Toolkit</p><h2 className="mt-3 text-4xl font-black">Turn the guide into a finished story.</h2></div><Link href="/works/haru-first-journey" className="w-fit rounded-full bg-white px-7 py-4 font-black text-[#6f4e37]">See the workflow in action</Link></div></section>
  </main>;
}
