import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import MusicPlayer from "../MusicPlayer";
import { getSoundtrack, soundtracks } from "@/lib/soundtrackDetails";

type Props = { params: Promise<{ slug: string }> };
export function generateStaticParams() { return soundtracks.map(track => ({ slug: track.slug })); }
export async function generateMetadata({ params }: Props): Promise<Metadata> { const track = getSoundtrack((await params).slug); if (!track) return {}; const title = `${track.title} | FourFeetz Music`; const cover = `/images/music/tracks/${track.slug}.png`; return { title, description: track.overview, alternates: { canonical: `/music/${track.slug}` }, openGraph: { title, description: track.overview, images: [cover] }, twitter: { card: "summary_large_image", title, description: track.overview, images: [cover] } }; }

function Heading({ eyebrow, title }: { eyebrow: string; title: string }) { return <div><p className="text-sm font-black uppercase tracking-[0.35em] text-[#a67c52]">{eyebrow}</p><h2 className="mt-3 text-4xl font-black tracking-tight text-[#2b2119] md:text-6xl">{title}</h2></div>; }

export default async function Page({ params }: Props) {
  const track = getSoundtrack((await params).slug); if (!track) notFound();
  const related = soundtracks.filter(item => item.slug !== track.slug).slice(0, 3);
  const cover = `/images/music/tracks/${track.slug}.png`;
  const schema = { "@context": "https://schema.org", "@type": "MusicRecording", name: track.title, duration: track.duration, image: cover, byArtist: { "@type": "Organization", name: "FourFeetz Studios" }, url: `https://fourfeetz.com/music/${track.slug}` };
  return <main><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} />
    <section className="mx-auto grid max-w-7xl gap-10 px-6 py-16 md:grid-cols-[0.92fr_0.88fr] md:items-center md:py-20"><div><p className="text-sm font-black uppercase tracking-[0.35em] text-[#a67c52]">Original Soundtrack</p><h1 className="mt-4 text-5xl font-black tracking-tight text-[#2b2119] md:text-7xl">{track.title}</h1><p className="mt-5 text-xl font-black text-[#6f4e37]">{track.status} · {track.duration}</p><p className="mt-6 max-w-2xl text-lg leading-8 text-[#76685d]">{track.overview}</p>{track.audio ? <MusicPlayer title={track.title} src={track.audio} /> : <p className="mt-8 inline-flex rounded-full border border-[#d8c3ad] bg-white px-5 py-3 text-sm font-black text-[#6f4e37]">Preview in production</p>}</div><div className="relative aspect-square overflow-hidden rounded-[32px] border border-[#eadfce] bg-white shadow-xl"><Image src={cover} alt={`${track.title} cover artwork`} fill priority sizes="(min-width: 768px) 560px, 100vw" className="object-contain p-5" /></div></section>
    <section className="border-y border-[#eadfce] bg-white px-6 py-20"><div className="mx-auto grid max-w-7xl gap-10 md:grid-cols-[0.42fr_0.58fr]"><Heading eyebrow="Mood" title="Emotional Direction" /><p className="text-2xl font-black leading-9 text-[#2b2119]">{track.mood}</p></div></section>
    <section className="px-6 py-20"><div className="mx-auto max-w-7xl"><Heading eyebrow="Production" title="Behind the Track" /><p className="mt-6 max-w-3xl text-lg leading-8 text-[#76685d]">{track.production}</p><div className="mt-8 rounded-3xl bg-[#2b2119] p-7 text-[#fffdf8]"><p className="text-sm font-black uppercase tracking-[0.2em] text-[#d8b892]">Music Prompt</p><p className="mt-4 font-mono leading-8">{track.prompt}</p></div></div></section>
    <section className="border-y border-[#eadfce] bg-white px-6 py-20"><div className="mx-auto max-w-7xl"><Heading eyebrow="Arrangement" title="Instruments & Usage" /><div className="mt-8 grid gap-5 md:grid-cols-2"><article className="rounded-3xl border border-[#eadfce] bg-[#fffdf8] p-7"><h3 className="text-2xl font-black text-[#2b2119]">Instruments</h3><ul className="mt-4 space-y-3 text-[#76685d]">{track.instruments.map(item => <li key={item}>- {item}</li>)}</ul></article><article className="rounded-3xl border border-[#eadfce] bg-[#fffdf8] p-7"><h3 className="text-2xl font-black text-[#2b2119]">Designed For</h3><ul className="mt-4 space-y-3 text-[#76685d]">{track.usage.map(item => <li key={item}>- {item}</li>)}</ul></article></div><article className="mt-5 rounded-3xl border border-[#eadfce] bg-white p-7"><h3 className="text-2xl font-black text-[#2b2119]">Lyrics</h3><p className="mt-4 leading-8 text-[#76685d]">This cue is intentionally instrumental. Its melodic phrasing leaves space for narration, natural sound, and the character&apos;s visual performance.</p></article></div></section>
    <section className="px-6 py-20"><div className="mx-auto max-w-7xl"><Heading eyebrow="Related Music" title="Continue Listening" /><div className="mt-8 grid gap-5 md:grid-cols-3">{related.map(item => <Link key={item.slug} href={`/music/${item.slug}`} className="rounded-3xl border border-[#eadfce] bg-white p-7 shadow-sm transition hover:-translate-y-1 hover:shadow-xl"><p className="text-sm font-black text-[#a67c52]">{item.status}</p><h3 className="mt-3 text-2xl font-black text-[#2b2119]">{item.title}</h3><p className="mt-3 text-[#76685d]">{item.mood}</p></Link>)}</div></div></section>
    <section className="px-6 pb-24"><div className="mx-auto flex max-w-7xl flex-col gap-6 rounded-[40px] bg-[#6f4e37] p-8 text-white md:flex-row md:items-center md:justify-between md:p-12"><div><p className="text-sm font-black uppercase tracking-[0.3em] text-[#e5c9a8]">Picture & Sound</p><h2 className="mt-3 text-4xl font-black">Experience the story behind the music.</h2></div><Link href="/works/haru-first-journey" className="w-fit rounded-full bg-white px-7 py-4 font-black text-[#6f4e37]">View HARU - First Journey</Link></div></section>
  </main>;
}
