export type MusicTrack = {
  slug: string;
  title: string;
  artist: string;
  category: string;
  duration: string;
  description: string;
  audio?: string;
  character?: string;
  featured: boolean;
  badge?: string;
  status: "Released" | "In Production";
  cover: string;
  mood: string;
  production: string;
  prompt: string;
  instruments: string[];
  usage: string[];
};

const rawMusicTracks: MusicTrack[] = [
  {
    slug: "haru-main-theme",
    title: "Sky Steps",
    artist: "FourFeetz Studios",
    category: "Official Soundtrack",
    duration: "4:39",
    description: "The official main theme for HARU, created to express the warmth, curiosity, and quiet sense of adventure at the heart of HARU’s journey.",
    audio: "/audio/haru/haru-main-theme.mp3",
    character: "HARU",
    featured: true,
    badge: "OFFICIAL THEME",
    status: "Released",
    cover: "/images/music/tracks/haru-theme.png",
    mood: "Warm, curious, and quietly adventurous",
    production: "The official theme was shaped around HARU’s emotional identity, balancing a gentle sense of discovery with the warmth of finding a place to belong.",
    prompt: "Warm cinematic character theme, gentle piano and acoustic textures, soft orchestral lift, curious and hopeful journey, quiet sense of adventure, instrumental.",
    instruments: ["Piano", "Acoustic textures", "Soft strings", "Cinematic ambience"],
    usage: ["HARU character theme", "HARU — First Journey", "Character introductions", "Official FourFeetz releases"],
  },
  {
    slug: "puppys-morning-adventure-1",
    title: "Puppy's Morning Adventure I",
    artist: "FourFeetz Studios",
    category: "Background Music",
    duration: "2:33",
    description: "A bright, gentle morning cue that follows HARU into the first curious moments of a new day.",
    audio: "/audio/haru/puppys-morning-adventure-1.mp3",
    character: "HARU",
    featured: false,
    badge: "ORIGINAL SOUNDTRACK",
    status: "Released",
    cover: "/images/music/tracks/haru-theme.png",
    mood: "Bright, playful, and warmly curious",
    production: "The first Morning Adventure arrangement builds a light cinematic arc around HARU's gentle movement and alert curiosity.",
    prompt: "Warm playful puppy morning instrumental, light piano, acoustic guitar, soft percussion, curious cinematic movement, no vocals.",
    instruments: ["Light piano", "Acoustic guitar", "Soft percussion", "Warm strings"],
    usage: ["Morning scenes", "Character exploration", "Gentle travel", "HARU background music"],
  },
  {
    slug: "puppys-morning-adventure-2",
    title: "Puppy's Morning Adventure II",
    artist: "FourFeetz Studios",
    category: "Background Music",
    duration: "1:00",
    description: "A concise variation with playful forward motion for HARU's small discoveries and cheerful morning steps.",
    audio: "/audio/haru/puppys-morning-adventure-2.mp3",
    character: "HARU",
    featured: false,
    badge: "ORIGINAL SOUNDTRACK",
    status: "Released",
    cover: "/images/music/tracks/haru-theme.png",
    mood: "Playful, lively, and optimistic",
    production: "This compact variation focuses on a quick melodic hook and clean pacing for short character moments.",
    prompt: "Playful cinematic puppy cue, quick piano motif, acoustic rhythm, gentle bounce, optimistic morning, instrumental.",
    instruments: ["Piano", "Acoustic rhythm", "Light percussion", "Soft bass"],
    usage: ["Short-form scenes", "Playful transitions", "Morning montage", "HARU background music"],
  },
  {
    slug: "puppys-morning-adventure-3",
    title: "Puppy's Morning Adventure III",
    artist: "FourFeetz Studios",
    category: "Background Music",
    duration: "0:52",
    description: "A soft final morning variation that brings HARU's playful adventure to a warm, settled close.",
    audio: "/audio/haru/puppys-morning-adventure-3.mp3",
    character: "HARU",
    featured: false,
    badge: "ORIGINAL SOUNDTRACK",
    status: "Released",
    cover: "/images/music/tracks/haru-theme.png",
    mood: "Gentle, content, and lightly playful",
    production: "The third variation resolves the morning motif with a softer arrangement and a compact cinematic ending.",
    prompt: "Gentle puppy morning finale, soft piano, acoustic guitar, delicate bells, warm resolution, instrumental.",
    instruments: ["Soft piano", "Acoustic guitar", "Delicate bells", "Warm pad"],
    usage: ["Morning endings", "Quiet discoveries", "Short-form outro", "HARU background music"],
  },
  {
    slug: "afternoon-window",
    title: "Afternoon Window",
    artist: "FourFeetz Studios",
    category: "Background Music",
    duration: "4:00",
    description: "A calm afternoon piece for quiet window light, restful interiors, and HARU's unhurried moments at home.",
    audio: "/audio/haru/afternoon-window.mp3",
    character: "HARU",
    featured: false,
    badge: "ORIGINAL SOUNDTRACK",
    status: "Released",
    cover: "/images/music/tracks/haru-theme.png",
    mood: "Calm, sunlit, and reflective",
    production: "The arrangement leaves generous space between phrases so natural ambience and slow visual pacing can remain present.",
    prompt: "Peaceful afternoon window instrumental, soft piano, warm room ambience, subtle acoustic texture, slow and reflective, no vocals.",
    instruments: ["Piano", "Ambient texture", "Soft strings", "Room tone"],
    usage: ["Window scenes", "Restful interiors", "Long-form relaxation", "HARU background music"],
  },
  {
    slug: "afternoon-window-guitar",
    title: "Afternoon Window (Piano Version)",
    artist: "FourFeetz Studios",
    category: "Background Music",
    duration: "3:51",
    description: "A piano-led variation of Afternoon Window with an intimate tone for reflective scenes and gentle daylight.",
    audio: "/audio/haru/afternoon-window-guitar.mp3",
    character: "HARU",
    featured: false,
    badge: "ORIGINAL SOUNDTRACK",
    status: "Released",
    cover: "/images/music/tracks/haru-theme.png",
    mood: "Intimate, tender, and contemplative",
    production: "This alternate version brings the melodic line forward with a more intimate, piano-centered balance.",
    prompt: "Intimate afternoon piano instrumental, soft room ambience, gentle daylight, reflective and warm, no vocals.",
    instruments: ["Piano", "Soft ambience", "Subtle strings", "Room tone"],
    usage: ["Reflective scenes", "Quiet interiors", "Character close-ups", "HARU background music"],
  },
  {
    slug: "porchlight-afternoon",
    title: "Porchlight Afternoon",
    artist: "FourFeetz Studios",
    category: "Background Music",
    duration: "1:00",
    description: "A warm porch-side cue for peaceful pauses, soft daylight, and the comfort of being close to home.",
    audio: "/audio/haru/porchlight-afternoon.mp3",
    character: "HARU",
    featured: false,
    badge: "ORIGINAL SOUNDTRACK",
    status: "Released",
    cover: "/images/music/tracks/haru-theme.png",
    mood: "Warm, homely, and quietly hopeful",
    production: "A compact acoustic arrangement supports calm exterior scenes without overpowering natural sound.",
    prompt: "Warm porch afternoon instrumental, acoustic guitar, gentle piano, soft breeze ambience, homely cinematic mood, no vocals.",
    instruments: ["Acoustic guitar", "Gentle piano", "Soft percussion", "Ambient texture"],
    usage: ["Porch scenes", "Homecoming moments", "Quiet transitions", "HARU background music"],
  },
  {
    slug: "porchlight-afternoon-ambient",
    title: "Porchlight Afternoon (Ambient Version)",
    artist: "FourFeetz Studios",
    category: "Background Music",
    duration: "1:00",
    description: "An ambient variation with wider space and softer motion for meditative HARU scenes and peaceful transitions.",
    audio: "/audio/haru/porchlight-afternoon-ambient.mp3",
    character: "HARU",
    featured: false,
    badge: "ORIGINAL SOUNDTRACK",
    status: "Released",
    cover: "/images/music/tracks/haru-theme.png",
    mood: "Airy, peaceful, and meditative",
    production: "The ambient version removes rhythmic emphasis and opens the mix for slow visuals, room tone, and natural atmosphere.",
    prompt: "Airy porch ambience, soft cinematic pads, distant piano, gentle afternoon atmosphere, meditative, no vocals.",
    instruments: ["Ambient pads", "Distant piano", "Soft texture", "Natural atmosphere"],
    usage: ["Meditative scenes", "Slow transitions", "Relaxation edits", "HARU background music"],
  },
  {
    slug: "haru-theme",
    title: "HARU Theme",
    artist: "FourFeetz Studios",
    category: "Original Soundtrack",
    duration: "2:14",
    description: "The central musical identity for HARU — First Journey begins with a small acoustic motif and grows into a gentle cinematic theme.",
    audio: "/audio/haru/haru-theme.mp3",
    character: "HARU",
    featured: false,
    status: "Released",
    cover: "/images/music/tracks/haru-theme.png",
    mood: "Warm, curious, and quietly hopeful",
    production: "The cue was developed from scene pacing first, then shaped with AI-assisted composition, selective arrangement, and edit-aware mastering.",
    prompt: "Gentle cinematic character theme, warm felt piano, soft acoustic guitar, light strings, 82 BPM, curious opening, hopeful middle, intimate ending, instrumental, narration-safe mix, no dramatic percussion.",
    instruments: ["Felt piano", "Acoustic guitar", "Light strings", "Soft percussion"],
    usage: ["HARU title sequence", "Character introductions", "Reflective travel scenes", "End-card reprise"],
  },
  {
    slug: "golden-summer-breeze",
    title: "Golden Summer Breeze",
    artist: "FourFeetz Studios",
    category: "Original Soundtrack",
    duration: "2:32",
    description: "A relaxed travel cue designed for countryside movement, warm landscapes, and moments where the story simply breathes.",
    audio: "/audio/music/golden-summer-breeze.mp3",
    character: "HARU",
    featured: false,
    status: "Released",
    cover: "/images/music/tracks/golden-summer-breeze.png",
    mood: "Open, sunlit, and gently nostalgic",
    production: "A loop-friendly harmonic bed was generated and then edited around visual transitions so the melody leaves room for natural ambience.",
    prompt: "Sunlit cinematic instrumental, brushed drums, mellow guitar, soft piano, subtle strings, 88 BPM, summer countryside atmosphere, gentle forward motion, clean loop point, no vocals.",
    instruments: ["Mellow guitar", "Brushed drums", "Piano", "Ambient strings"],
    usage: ["Travel montages", "Country-road scenes", "Studio reels", "Long-form background"],
  },
  {
    slug: "country-road",
    title: "Country Road",
    artist: "FourFeetz Studios",
    category: "Original Soundtrack",
    duration: "2:08",
    description: "A rhythmic cue for walking sequences and small discoveries along HARU's route.",
    character: "HARU",
    featured: false,
    status: "In Production",
    cover: "/images/music/tracks/country-road.png",
    mood: "Playful movement with a grounded folk rhythm",
    production: "The arrangement is being tested against several walking tempos before the final melody and mix are locked.",
    prompt: "Light folk-cinematic instrumental, fingerpicked guitar, soft hand percussion, warm bass, 92 BPM, steady walking rhythm, playful but natural, no vocals.",
    instruments: ["Fingerpicked guitar", "Hand percussion", "Warm bass", "Mandolin accents"],
    usage: ["Walking montage", "Road transitions", "Outdoor shorts", "Behind-the-scenes edits"],
  },
  {
    slug: "golden-sunset",
    title: "Golden Sunset",
    artist: "FourFeetz Studios",
    category: "Original Soundtrack",
    duration: "1:58",
    description: "A restrained sunset cue that supports wonder without telling the audience what to feel.",
    character: "HARU",
    featured: false,
    status: "In Production",
    cover: "/images/music/tracks/golden-sunset.png",
    mood: "Tender, spacious, and cinematic",
    production: "Long tones and sparse piano are arranged around visual holds, with the climax kept intentionally small.",
    prompt: "Tender cinematic underscore, sparse piano, airy strings, distant guitar harmonics, 68 BPM, golden sunset, quiet emotional lift, instrumental, wide dynamic space.",
    instruments: ["Sparse piano", "Airy strings", "Guitar harmonics", "Ambient texture"],
    usage: ["Sunset scenes", "Emotional transitions", "Final landscape shots", "Character reflection"],
  },
  {
    slug: "coming-home",
    title: "Coming Home",
    artist: "FourFeetz Studios",
    category: "Original Soundtrack",
    duration: "2:26",
    description: "A homecoming theme built to resolve the film's musical ideas with warmth rather than spectacle.",
    character: "HARU",
    featured: false,
    status: "In Production",
    cover: "/images/music/tracks/coming-home.png",
    mood: "Reassuring, resolved, and intimate",
    production: "The cue reprises HARU's motif at a slower tempo and moves from uncertainty toward a settled final chord.",
    prompt: "Intimate homecoming score, felt piano reprise, warm cello, acoustic guitar, 72 BPM, reassuring resolution, gentle emotional arc, instrumental, soft ending.",
    instruments: ["Felt piano", "Cello", "Acoustic guitar", "Room ambience"],
    usage: ["Arrival scenes", "Emotional resolution", "Family moments", "Closing narration"],
  },
  {
    slug: "end-credits",
    title: "End Credits",
    artist: "FourFeetz Studios",
    category: "Original Soundtrack",
    duration: "1:41",
    description: "A concise end-credit arrangement that gathers the film's key motifs into a clean, shareable finish.",
    character: "HARU",
    featured: false,
    status: "In Production",
    cover: "/images/music/tracks/end-credits.png",
    mood: "Bright, memorable, and complete",
    production: "Theme fragments are reordered for a faster opening, readable credit timing, and a definitive final button.",
    prompt: "Warm cinematic end credits, character theme reprise, piano, guitar, light strings and percussion, 86 BPM, uplifting but refined, memorable final cadence, instrumental.",
    instruments: ["Piano", "Guitar", "Strings", "Light percussion"],
    usage: ["End credits", "Release trailer", "Social cutdown", "Studio ident"],
  },
];

export const musicTracks: MusicTrack[] = rawMusicTracks.map((track) =>
  track.featured
    ? track
    : { ...track, badge: "ORIGINAL SOUNDTRACK", category: "Background Music" },
);

export function getMusicTrack(slug: string) {
  return musicTracks.find((track) => track.slug === slug);
}
