export type MusicTrack = {
  slug: string;
  title: string;
  artist: string;
  category: "Official Soundtrack" | "Original Soundtrack";
  duration: string;
  description: string;
  audio: string;
  character: string;
  featured: boolean;
  badge: "OFFICIAL THEME" | "ORIGINAL SOUNDTRACK";
  status: "Released";
  cover: string;
  mood: string;
  production: string;
  prompt?: string;
  instruments?: string[];
  usage: string[];
  publishedAt?: string;
  updatedAt?: string;
  publishStatus?: "published" | "draft";
};

const haruCover = "/images/music/tracks/haru-theme.png";

export const musicTracks: MusicTrack[] = [
  {
    slug: "snowy-hearth-nap",
    title: "Snowy Hearth Nap",
    artist: "FourFeetz Studios",
    category: "Original Soundtrack",
    duration: "4:05",
    description: "A gentle winter relaxation theme created for HARU's quiet nap beside the fireplace, with soft space for crackling logs, snowfall, and natural room ambience.",
    audio: "/audio/haru/snowy-hearth-nap.mp3",
    character: "HARU",
    featured: false,
    badge: "ORIGINAL SOUNDTRACK",
    status: "Released",
    cover: "/images/works/haru-relax-moments-ep03/first-shot.webp",
    mood: "Warm, sleepy, intimate, and peaceful",
    production: "The arrangement was kept slow and unobtrusive so the fireplace, HARU's yawn, and the stillness of the winter room remain part of the listening experience.",
    instruments: ["Felt piano", "Warm ambient pads", "Delicate celesta", "Subtle strings"],
    usage: ["HARU — Snowy Hearth Nap", "FourFeetz Relax Moments", "Winter relaxation", "Quiet study and rest"],
    publishedAt: "2026-07-23",
    updatedAt: "2026-07-23",
    publishStatus: "published",
  },
  {
    slug: "haru-main-theme",
    title: "HARU Main Theme",
    artist: "FourFeetz Studios",
    category: "Official Soundtrack",
    duration: "4:39",
    description: "The official main theme for HARU, created to express the warmth, curiosity, and quiet sense of adventure at the heart of HARU's journey.",
    audio: "/audio/haru/haru-main-theme.mp3",
    character: "HARU",
    featured: true,
    badge: "OFFICIAL THEME",
    status: "Released",
    cover: "/images/music/tracks/haru-main-theme.png",
    mood: "Warm, curious, and quietly adventurous",
    production: "The official theme was shaped around HARU's emotional identity, balancing a gentle sense of discovery with the warmth of finding a place to belong.",
    publishedAt: "2026-07-17",
    publishStatus: "published",
    prompt: "Warm cinematic character theme, gentle piano and acoustic textures, soft orchestral lift, curious and hopeful journey, quiet sense of adventure, instrumental.",
    instruments: ["Piano", "Acoustic textures", "Soft strings", "Cinematic ambience"],
    usage: ["HARU character theme", "HARU — First Journey", "Character introductions", "Official FourFeetz releases"],
  },
  {
    slug: "window-cat-paws",
    title: "Window Cat Paws",
    artist: "FourFeetz Studios",
    category: "Original Soundtrack",
    duration: "0:59",
    description: "The original soundtrack for LUNA Shorts EP.01, following LUNA's quiet watchfulness and the moment curiosity draws her beyond the window.",
    audio: "/audio/music/window-cat-paws.mp3",
    character: "LUNA",
    featured: false,
    badge: "ORIGINAL SOUNDTRACK",
    status: "Released",
    cover: "/images/shorts/luna/luna-shorts-ep01-cover.png",
    mood: "Quiet, observant, and gently curious",
    production: "Window Cat Paws supports the restrained pacing of LUNA Shorts EP.01, moving with her watchful pause and the story's final turn toward curiosity.",
    publishedAt: "2026-07-22",
    publishStatus: "published",
    usage: ["LUNA Shorts EP.01", "LUNA character moments", "Quiet window scenes", "Vertical short films"],
  },
  {
    slug: "puppys-morning-adventure-1",
    title: "Puppy's Morning Adventure I",
    artist: "FourFeetz Studios",
    category: "Original Soundtrack",
    duration: "2:33",
    description: "A bright, gentle morning cue that follows HARU into the first curious moments of a new day.",
    audio: "/audio/haru/puppys-morning-adventure-1.mp3",
    character: "HARU",
    featured: false,
    badge: "ORIGINAL SOUNDTRACK",
    status: "Released",
    cover: haruCover,
    mood: "Bright, playful, and warmly curious",
    production: "A light cinematic arrangement built around HARU's gentle movement and alert curiosity.",
    prompt: "Warm playful puppy morning instrumental, light piano, acoustic guitar, soft percussion, curious cinematic movement, no vocals.",
    instruments: ["Light piano", "Acoustic guitar", "Soft percussion", "Warm strings"],
    usage: ["Morning scenes", "Character exploration", "Gentle travel", "HARU background music"],
  },
  {
    slug: "puppys-morning-adventure-2",
    title: "Puppy's Morning Adventure II",
    artist: "FourFeetz Studios",
    category: "Original Soundtrack",
    duration: "1:00",
    description: "A concise variation with playful forward motion for HARU's small discoveries and cheerful morning steps.",
    audio: "/audio/haru/puppys-morning-adventure-2.mp3",
    character: "HARU",
    featured: false,
    badge: "ORIGINAL SOUNDTRACK",
    status: "Released",
    cover: haruCover,
    mood: "Playful, lively, and optimistic",
    production: "A compact variation focused on a quick melodic hook and clean pacing for short character moments.",
    prompt: "Playful cinematic puppy cue, quick piano motif, acoustic rhythm, gentle bounce, optimistic morning, instrumental.",
    instruments: ["Piano", "Acoustic rhythm", "Light percussion", "Soft bass"],
    usage: ["Short-form scenes", "Playful transitions", "Morning montage", "HARU background music"],
  },
  {
    slug: "puppys-morning-adventure-3",
    title: "Puppy's Morning Adventure III",
    artist: "FourFeetz Studios",
    category: "Original Soundtrack",
    duration: "0:52",
    description: "A soft final morning variation that brings HARU's playful adventure to a warm, settled close.",
    audio: "/audio/haru/puppys-morning-adventure-3.mp3",
    character: "HARU",
    featured: false,
    badge: "ORIGINAL SOUNDTRACK",
    status: "Released",
    cover: haruCover,
    mood: "Gentle, content, and lightly playful",
    production: "The morning motif resolves through a softer arrangement and a compact cinematic ending.",
    prompt: "Gentle puppy morning finale, soft piano, acoustic guitar, delicate bells, warm resolution, instrumental.",
    instruments: ["Soft piano", "Acoustic guitar", "Delicate bells", "Warm pad"],
    usage: ["Morning endings", "Quiet discoveries", "Short-form outro", "HARU background music"],
  },
  {
    slug: "afternoon-window",
    title: "Afternoon Window",
    artist: "FourFeetz Studios",
    category: "Original Soundtrack",
    duration: "4:00",
    description: "A calm afternoon piece for quiet window light, restful interiors, and HARU's unhurried moments at home.",
    audio: "/audio/haru/afternoon-window.mp3",
    character: "HARU",
    featured: false,
    badge: "ORIGINAL SOUNDTRACK",
    status: "Released",
    cover: haruCover,
    mood: "Calm, sunlit, and reflective",
    production: "Generous space between phrases leaves room for natural ambience and slow visual pacing.",
    prompt: "Peaceful afternoon window instrumental, soft piano, warm room ambience, subtle acoustic texture, slow and reflective, no vocals.",
    instruments: ["Piano", "Ambient texture", "Soft strings", "Room tone"],
    usage: ["Window scenes", "Restful interiors", "Long-form relaxation", "HARU background music"],
  },
  {
    slug: "afternoon-window-guitar-version",
    title: "Afternoon Window (Guitar Version)",
    artist: "FourFeetz Studios",
    category: "Original Soundtrack",
    duration: "3:51",
    description: "A guitar-led variation of Afternoon Window with an intimate warmth for reflective scenes and gentle daylight.",
    audio: "/audio/haru/afternoon-window-guitar.mp3",
    character: "HARU",
    featured: false,
    badge: "ORIGINAL SOUNDTRACK",
    status: "Released",
    cover: haruCover,
    mood: "Intimate, tender, and contemplative",
    production: "This alternate version brings the acoustic guitar forward for a warmer and more personal balance.",
    prompt: "Intimate afternoon acoustic guitar instrumental, soft room ambience, gentle daylight, reflective and warm, no vocals.",
    instruments: ["Acoustic guitar", "Soft ambience", "Subtle strings", "Room tone"],
    usage: ["Reflective scenes", "Quiet interiors", "Character close-ups", "HARU background music"],
  },
  {
    slug: "porchlight-afternoon",
    title: "Porchlight Afternoon",
    artist: "FourFeetz Studios",
    category: "Original Soundtrack",
    duration: "1:00",
    description: "A warm porch-side cue for peaceful pauses, soft daylight, and the comfort of being close to home.",
    audio: "/audio/haru/porchlight-afternoon.mp3",
    character: "HARU",
    featured: false,
    badge: "ORIGINAL SOUNDTRACK",
    status: "Released",
    cover: haruCover,
    mood: "Warm, homely, and quietly hopeful",
    production: "A compact acoustic arrangement supports calm exterior scenes without overpowering natural sound.",
    prompt: "Warm porch afternoon instrumental, acoustic guitar, gentle piano, soft breeze ambience, homely cinematic mood, no vocals.",
    instruments: ["Acoustic guitar", "Gentle piano", "Soft percussion", "Ambient texture"],
    usage: ["Porch scenes", "Homecoming moments", "Quiet transitions", "HARU background music"],
  },
  {
    slug: "porchlight-afternoon-ambient-version",
    title: "Porchlight Afternoon (Ambient Version)",
    artist: "FourFeetz Studios",
    category: "Original Soundtrack",
    duration: "1:00",
    description: "An ambient variation with wider space and softer motion for meditative HARU scenes and peaceful transitions.",
    audio: "/audio/haru/porchlight-afternoon-ambient.mp3",
    character: "HARU",
    featured: false,
    badge: "ORIGINAL SOUNDTRACK",
    status: "Released",
    cover: haruCover,
    mood: "Airy, peaceful, and meditative",
    production: "The ambient version removes rhythmic emphasis and opens the mix for slow visuals and natural atmosphere.",
    prompt: "Airy porch ambience, soft cinematic pads, distant piano, gentle afternoon atmosphere, meditative, no vocals.",
    instruments: ["Ambient pads", "Distant piano", "Soft texture", "Natural atmosphere"],
    usage: ["Meditative scenes", "Slow transitions", "Relaxation edits", "HARU background music"],
  },
];

export function getMusicTrack(slug: string) {
  return musicTracks.find((track) => track.slug === slug);
}
