import type { Metadata } from "next";
import { englishLanguageAlternates } from "@/lib/localization";

export type ResourceDetail = {
  slug: string; title: string; category: string; description: string; image: string;
  overview: string; preview: string[]; howTo: string[]; bestPractices: string[];
  faq: { question: string; answer: string }[];
  publishedAt?: string;
  updatedAt?: string;
  featured?: boolean;
  publishStatus?: "published" | "draft";
};

export const resourceDetails: ResourceDetail[] = [
  { slug: "character-consistency-prompt-pack", title: "Character Consistency Planning Framework", category: "Public Framework", description: "A public planning outline for reviewing identity, wardrobe, proportions, and visual continuity across generated scenes.", image: "/images/resources/character-consistency-prompt-pack.svg", overview: "This web guide separates stable visual traits from scene-specific direction so creators can review continuity without copying FourFeetz character prompts or internal bibles.", preview: ["Observable identity fields", "Reference-view planning", "Expression and wardrobe checks", "Common identity-drift review points"], howTo: ["Define only the visible traits needed for your own original character.", "Build one approved reference image for the intended shot scale.", "Keep stable visual traits separate from scene action and camera direction.", "Change one scene variable at a time while testing.", "Review face, proportions, colors, and accessories before approving a frame."], bestPractices: ["Use observable visual language instead of personality adjectives.", "Keep accessory names and colors identical.", "Reuse approved references when the tool supports them.", "Archive approved frames as future review evidence."], faq: [{ question: "Does this work across different models?", answer: "The review structure is model-neutral, although reference-image controls vary by platform." }, { question: "Does this include FourFeetz character prompts?", answer: "No. FourFeetz master prompts, internal character bibles, weighting logic, and current core settings remain private." }] },
  { slug: "image-to-video-prompt-framework", title: "Image-to-Video Prompt Framework", category: "AI Video Guide", description: "A practical structure for directing subject motion, camera movement, environment, lighting, and continuity.", image: "/images/resources/image-to-video-prompt-framework.svg", overview: "Image-to-video prompts work best as motion direction, not as a second image description. This framework tells the model what changes, what stays fixed, and how the camera observes the action.", preview: ["Subject motion field", "Camera direction field", "Environmental motion field", "Continuity and negative-motion checks"], howTo: ["Start from a clean, approved reference frame.", "Choose one subject action and one camera move.", "Describe timing with words such as slow, steady, or gradual.", "Add only environmental motion that supports the shot.", "State which face, outfit, and background details must remain stable."], bestPractices: ["Keep clips short while testing motion.", "Avoid conflicting camera directions.", "Write physical actions in chronological order.", "Use the last approved frame to continue a sequence."], faq: [{ question: "Should I repeat the image description?", answer: "Only repeat identity details that must not change. Spend most of the prompt on motion and timing." }, { question: "Can I request several actions?", answer: "One primary action per shot is more reliable and easier to edit." }] },
  { slug: "ai-short-film-workflow", title: "AI Short Film Workflow", category: "Workflow", description: "A repeatable production pipeline from story and reference development to animation, sound, editing, and publishing.", image: "/images/resources/ai-short-film-workflow.svg", overview: "The workflow turns an idea into a sequence of reviewable production gates. Each stage creates an approved asset for the next, reducing expensive regeneration late in the edit.", preview: ["Story brief and emotional arc", "Shot list and reference board", "Image and motion approval gates", "Sound, edit, and delivery checklist"], howTo: ["Write a one-sentence story promise.", "Break the story into six to twelve essential shots.", "Approve character and environment references.", "Generate stills before committing to motion.", "Edit a silent animatic, then add voice, music, and effects.", "Export a master before creating platform variants."], bestPractices: ["Name every asset by scene and version.", "Review continuity between adjacent shots.", "Lock music after the story edit is stable.", "Keep a production log of prompts and model settings."], faq: [{ question: "How long should a first AI short be?", answer: "Thirty to ninety seconds is enough to test a complete workflow without creating an unmanageable shot count." }, { question: "When should music be generated?", answer: "Sketch mood early, but finalize music after picture timing is close to locked." }] },
  { slug: "storyboard-planning-template", title: "Storyboard Planning Template", category: "Template", description: "An editorial planning sheet for framing, action, camera direction, sound, transitions, and continuity.", image: "/images/resources/storyboard-planning-template.svg", overview: "The template makes every shot answer a story question before generation begins. It connects visual composition to duration, motion, audio, and the next edit point.", preview: ["Four-frame storyboard rows", "Shot size and lens fields", "Character and camera direction", "Sound, duration, and transition notes"], howTo: ["Write the scene objective at the top.", "Sketch one readable action in each frame.", "Mark shot size and camera movement.", "Record continuity details that carry into the next frame.", "Estimate duration and identify required sound."], bestPractices: ["Storyboard the edit, not every imagined moment.", "Alternate wide, medium, and close framing intentionally.", "Keep screen direction consistent.", "Flag difficult shots for early testing."], faq: [{ question: "Do the drawings need to look polished?", answer: "No. Clear staging and camera intent matter more than illustration quality." }, { question: "Can this be used for vertical video?", answer: "Yes. Set the frame field to 9:16 and mark title and caption safe zones." }] },
  { slug: "character-production-checklist", title: "Character Production Checklist", category: "Checklist", description: "A practical quality-control list for identity, motion, voice, music, continuity, and final delivery.", image: "/images/resources/character-production-checklist.svg", overview: "The checklist catches subtle character drift before it reaches animation or editing. It is designed for scene reviews, handoffs, and final delivery checks.", preview: ["Identity and proportion review", "Wardrobe and accessory continuity", "Motion and expression checks", "Voice, sound, and export review"], howTo: ["Create a copy for each scene.", "Review the still image before animation.", "Repeat the review on the first and final video frames.", "Record failures and the corrective prompt.", "Complete delivery checks for every aspect ratio."], bestPractices: ["Assign one person as continuity owner.", "Compare against the master reference at full size.", "Check silhouettes as well as facial details.", "Do not approve a shot with unresolved identity drift."], faq: [{ question: "When should the checklist be used?", answer: "At still approval, motion approval, edit lock, and final export." }, { question: "Is it useful for one-person teams?", answer: "Yes. It provides a consistent review routine when you switch between creative and quality-control roles." }] },
  { slug: "ai-music-prompt-starter-pack", title: "AI Music Direction Guide", category: "Public Planning Guide", description: "A public framework for defining scene function, emotional restraint, structure, ambience space, and rights review before testing AI-assisted music.", image: "/images/resources/ai-music-prompt-starter-pack.svg", overview: "This web guide turns a scene purpose into reviewable music direction through tempo, instrumentation, structure, dynamics, exclusions, and licensing checks. It is not a downloadable prompt pack and does not include private FourFeetz music-production assets.", preview: ["Scene function and emotional restraint", "Tempo and instrumentation fields", "Structure and ambience-space notes", "Rights and delivery review"], howTo: ["Define what the music should do for the scene in one sentence.", "Choose a tempo range and a small instrument family.", "Describe the structural lift, resolution, and intended duration.", "Reserve space for dialogue, ambience, and sound effects.", "Review rights and export records before using a selected result."], bestPractices: ["Describe scene function before genre.", "Keep arrangements restrained when picture and ambience carry the emotion.", "Test clean endings or loop points inside the edit.", "Keep licensing records for every exported track."], faq: [{ question: "Can generated music be used commercially?", answer: "Usage rights depend on the tool and subscription. Verify the current license for each exported track." }, { question: "Does this page include FourFeetz music prompts?", answer: "No. It shares general direction and review fields, while private prompts, project files, and current studio settings remain protected." }] },
  { slug: "vertical-video-reframing-guide", title: "16:9 to 9:16 Reframing Guide", category: "Social Video", description: "A production guide for adapting cinematic masters to Shorts, Reels, TikTok, and Naver Clip without losing the subject.", image: "/images/resources/vertical-video-reframing-guide.svg", overview: "Vertical delivery is a new composition, not a center crop. This guide combines AI reframing, scene expansion, manual keyframes, and subtitle-safe review.", preview: ["Platform export specifications", "Subject-safe framing overlays", "AI reframe and manual-edit workflow", "Subtitle and interface safe zones"], howTo: ["Duplicate the 16:9 master timeline.", "Create a 1080 by 1920 sequence.", "Track the subject and set a deliberate vertical composition.", "Expand backgrounds when a crop removes story context.", "Review every frame with captions and platform overlays."], bestPractices: ["Protect faces and eyelines.", "Preserve movement direction.", "Reposition captions shot by shot.", "Export from the master-quality source."], faq: [{ question: "Is automatic reframing enough?", answer: "It is a useful first pass, but character shots and fast movement still require manual review." }, { question: "Should I shoot vertical separately?", answer: "For critical social-first scenes, a dedicated vertical composition often produces the best result." }] },
  { slug: "production-notes-template", title: "FourFeetz Production Notes Worksheet", category: "Public Worksheet", description: "A browser-readable outline for recording scene goals, references, visible problems, review decisions, and final outcomes.", image: "/images/resources/production-notes-template.svg", overview: "Production notes make review decisions traceable. This public worksheet focuses on transferable documentation fields and does not contain FourFeetz prompts, internal paths, character bibles, or current core settings.", preview: ["Scene objective and public reference links", "Tool and model context", "Camera, sound, and continuity notes", "Visible issue, decision, and next-action fields"], howTo: ["Create one record per approved shot or representative experiment.", "Keep private prompts and internal asset paths in your own protected system.", "Link only references and exported versions that are safe to share.", "Document what failed as clearly as what worked.", "Close each record with a practical review decision."], bestPractices: ["Use consistent scene and version names.", "Record relevant model context and generation dates.", "Separate observations from decisions.", "Keep private settings with the protected production asset, not the public worksheet."], faq: [{ question: "How much detail is enough?", answer: "Capture enough visible context to explain the result and the review decision without exposing proprietary assets." }, { question: "Should failed generations be logged?", answer: "Log representative failures when they reveal a repeatable limitation or useful correction." }] },
];

export function getResource(slug: string) { return resourceDetails.find(item => item.slug === slug); }

export function createResourceMetadata(resource: ResourceDetail): Metadata {
  const path = `/resources/${resource.slug}`;
  const title = `${resource.title} | FourFeetz Studios`;
  return {
    title: { absolute: title },
    description: resource.description,
    alternates: englishLanguageAlternates(path, `/ko/resources/${resource.slug}`),
    openGraph: {
      type: "website",
      title,
      description: resource.description,
      url: path,
      images: [{ url: resource.image, alt: `${resource.title} resource preview` }],
    },
    twitter: {
      card: "summary_large_image",
      title,
      description: resource.description,
      images: [resource.image],
    },
  };
}
