export type Soundtrack = { slug: string; title: string; duration: string; status: string; mood: string; overview: string; production: string; prompt: string; instruments: string[]; usage: string[]; audio?: string };

export const soundtracks: Soundtrack[] = [
  { slug: "haru-theme", title: "HARU Theme", duration: "2:14", status: "Released", mood: "Warm, curious, and quietly hopeful", overview: "The central musical identity for HARU - First Journey begins with a small acoustic motif and grows into a gentle cinematic theme.", production: "The cue was developed from scene pacing first, then shaped with AI-assisted composition, selective arrangement, and edit-aware mastering.", prompt: "Gentle cinematic character theme, warm felt piano, soft acoustic guitar, light strings, 82 BPM, curious opening, hopeful middle, intimate ending, instrumental, narration-safe mix, no dramatic percussion.", instruments: ["Felt piano", "Acoustic guitar", "Light strings", "Soft percussion"], usage: ["HARU title sequence", "Character introductions", "Reflective travel scenes", "End-card reprise"], audio: "/audio/haru/haru-theme.mp3" },
  { slug: "golden-summer-breeze", title: "Golden Summer Breeze", duration: "2:32", status: "Released", mood: "Open, sunlit, and gently nostalgic", overview: "A relaxed travel cue designed for countryside movement, warm landscapes, and moments where the story simply breathes.", production: "A loop-friendly harmonic bed was generated and then edited around visual transitions so the melody leaves room for natural ambience.", prompt: "Sunlit cinematic instrumental, brushed drums, mellow guitar, soft piano, subtle strings, 88 BPM, summer countryside atmosphere, gentle forward motion, clean loop point, no vocals.", instruments: ["Mellow guitar", "Brushed drums", "Piano", "Ambient strings"], usage: ["Travel montages", "Country-road scenes", "Studio reels", "Long-form background"], audio: "/audio/music/golden-summer-breeze.mp3" },
  { slug: "country-road", title: "Country Road", duration: "2:08", status: "In Production", mood: "Playful movement with a grounded folk rhythm", overview: "A rhythmic cue for walking sequences and small discoveries along HARU's route.", production: "The arrangement is being tested against several walking tempos before the final melody and mix are locked.", prompt: "Light folk-cinematic instrumental, fingerpicked guitar, soft hand percussion, warm bass, 92 BPM, steady walking rhythm, playful but natural, no vocals.", instruments: ["Fingerpicked guitar", "Hand percussion", "Warm bass", "Mandolin accents"], usage: ["Walking montage", "Road transitions", "Outdoor shorts", "Behind-the-scenes edits"] },
  { slug: "golden-sunset", title: "Golden Sunset", duration: "1:58", status: "In Production", mood: "Tender, spacious, and cinematic", overview: "A restrained sunset cue that supports wonder without telling the audience what to feel.", production: "Long tones and sparse piano are arranged around visual holds, with the climax kept intentionally small.", prompt: "Tender cinematic underscore, sparse piano, airy strings, distant guitar harmonics, 68 BPM, golden sunset, quiet emotional lift, instrumental, wide dynamic space.", instruments: ["Sparse piano", "Airy strings", "Guitar harmonics", "Ambient texture"], usage: ["Sunset scenes", "Emotional transitions", "Final landscape shots", "Character reflection"] },
  { slug: "coming-home", title: "Coming Home", duration: "2:26", status: "In Production", mood: "Reassuring, resolved, and intimate", overview: "A homecoming theme built to resolve the film's musical ideas with warmth rather than spectacle.", production: "The cue reprises HARU's motif at a slower tempo and moves from uncertainty toward a settled final chord.", prompt: "Intimate homecoming score, felt piano reprise, warm cello, acoustic guitar, 72 BPM, reassuring resolution, gentle emotional arc, instrumental, soft ending.", instruments: ["Felt piano", "Cello", "Acoustic guitar", "Room ambience"], usage: ["Arrival scenes", "Emotional resolution", "Family moments", "Closing narration"] },
  { slug: "end-credits", title: "End Credits", duration: "1:41", status: "In Production", mood: "Bright, memorable, and complete", overview: "A concise end-credit arrangement that gathers the film's key motifs into a clean, shareable finish.", production: "Theme fragments are reordered for a faster opening, readable credit timing, and a definitive final button.", prompt: "Warm cinematic end credits, character theme reprise, piano, guitar, light strings and percussion, 86 BPM, uplifting but refined, memorable final cadence, instrumental.", instruments: ["Piano", "Guitar", "Strings", "Light percussion"], usage: ["End credits", "Release trailer", "Social cutdown", "Studio ident"] },
];

export function getSoundtrack(slug: string) { return soundtracks.find(track => track.slug === slug); }
