import type { ProductionInsight } from "@/lib/productionInsights";

export const studioWorkflowInsightSlugs = [
  "from-first-image-to-final-short",
  "animal-character-short-publishing-checklist",
  "why-we-keep-animal-motions-simple",
  "turning-short-scene-into-relaxing-video",
  "what-we-keep-private-character-production",
] as const;

export type StudioWorkflowInsightSlug = (typeof studioWorkflowInsightSlugs)[number];
type Language = "en" | "ko";
type StudioWorkflowInsight = ProductionInsight & {
  heroAlt: string;
  heroCaption?: string;
  heroFit?: "cover" | "contain";
  heroPosition?: string;
};

const shared = {
  published: "2026-08-15",
  updated: "2026-08-15",
  category: "Production Notes",
} as const;

const koreanShared = {
  published: "2026-08-15",
  updated: "2026-08-15",
  category: "제작 노트",
} as const;

export const studioWorkflowInsights: Record<
  StudioWorkflowInsightSlug,
  Record<Language, StudioWorkflowInsight>
> = {
  "from-first-image-to-final-short": {
    en: {
      ...shared,
      slug: "from-first-image-to-final-short",
      eyebrow: "FourFeetz Scene Planning",
      title: "From First Image to Final Short: How FourFeetz Plans a Character Scene",
      shortTitle: "From First Image to Final Short",
      description: "A real FourFeetz scene-planning walkthrough: choosing a reference image, defining one action, protecting composition, and assembling the approved result into a finished short.",
      hero: "/images/insights/studio-workflow/first-image-to-final-short-board.png",
      heroAlt: "Three-stage FourFeetz production board connecting a rainy-window First Shot, scene plan and finished short",
      heroCaption: "An editorial production board showing the public workflow from approved First Shot to one-action scene plan and finished vertical short; no private prompt or setting is shown.",
      heroPosition: "50% 50%",
      readTime: "8 min read",
      verdict: "FourFeetz plans a short backward from its scene purpose. An approved reference establishes identity and composition, one action keeps motion reviewable, and the edit decides whether the generated clip actually belongs in the finished story.",
      tags: ["Scene Planning", "First Shot", "AI Shorts", "Character Consistency"],
      keywords: ["animal character scene planning", "First Shot workflow", "FourFeetz Shorts", "AI character continuity"],
      tools: ["Google Flow", "CapCut"],
      characters: ["HARU", "LUNA"],
      sections: [
        {
          id: "what-we-tested",
          title: "What We Tested: Starting With Purpose, Not Motion",
          paragraphs: [
            "The published HARU and LUNA rainy-window short began with a quiet shared pause, not with a request for impressive movement. The scene needed to introduce both characters, keep the rain outside the window and leave enough visual calm for the original music. That purpose determined the reference frame, camera distance and vertical composition before video generation began.",
            "We use an approved character image or an actual frame from the sequence as visible evidence. For this short, HARU and LUNA had to remain readable together at phone size. We checked their relative scale, face direction, window placement and the open space around their ears and paws. This is the public decision process; the finished character prompts and internal reference system remain private.",
          ],
          images: [
            { src: "/images/insights/haru-luna-rainy-window-01-opening.webp", alt: "Opening frame of HARU and LUNA resting beside a rainy window", caption: "The real opening frame establishes both characters, the window boundary and the quiet emotional purpose of the scene.", aspect: "video" },
          ],
        },
        {
          id: "what-went-wrong",
          title: "What Went Wrong: Letting One Shot Carry the Whole Story",
          paragraphs: [
            "When a short shot is asked to introduce the room, move two animals, change their expressions and move the camera, every layer can drift at once. Different reaction timing can become synchronized, a paw can lose contact with the floor, or the rainy window can be reconstructed as a different background. A visually polished result is still rejected when those changes weaken the scene connection.",
            "We also avoid choosing a reference only because it is the prettiest image. A close portrait may protect the face but provide no room for the planned action; a wide frame may show the environment but make a name tag or expression unreadable. The correct First Shot is the one that supports the intended edit.",
          ],
          bullets: ["One scene purpose", "One primary action", "A camera position that can remain stable", "Enough room for ears, paws and the vertical safe area"],
        },
        {
          id: "what-worked",
          title: "What Worked: Reference, One Action, Then Edit",
          paragraphs: [
            "Our stable order is reference approval, scene purpose, one observable action, motion review and final edit. In the rainy-window short, restrained glances and small posture changes gave each character separate timing without turning the moment into a performance. The generated material was judged beside the preceding and following shots, not as an isolated clip.",
            "CapCut was used for selecting usable ranges, trimming starts and endings, arranging the scene order and balancing the original music. Editing can improve rhythm and make a valid transition feel intentional. It cannot restore a changed face, missing paw or broken window geometry, so clips with structural failures do not advance to finishing.",
          ],
          steps: ["Choose a verified character or sequence reference.", "Write the emotional purpose of the scene in one sentence.", "Select one primary action and a clear end state.", "Compare opening, middle and final frames with the reference.", "Place only approved material in the real vertical edit."],
          videos: [
            { src: "/videos/shorts/haru-luna/haru-luna-rainy-evening-vertical-v2.mp4", poster: "/images/shorts/haru-luna/haru-luna-rainy-evening-vertical-v2-poster.webp", title: "A Quiet Rainy Evening with HARU and LUNA", caption: "The finished FourFeetz short used to validate the scene order, restrained character timing and final vertical composition.", presentation: "portrait" },
          ],
        },
        {
          id: "practical-takeaway",
          title: "Practical Takeaway: Approve What the Edit Needs",
          paragraphs: [
            "A First Shot is not complete because it looks cinematic. It is complete when it protects the character, makes the planned action physically possible and can connect to the neighboring material. Reviewing at phone size catches different problems from reviewing a full-resolution frame, so FourFeetz uses both views before accepting a scene.",
            "Creators can apply the same method without a private prompt system: define the scene purpose, mark identity details that must remain visible, limit the action and test the result inside the final aspect ratio. The finished short, character pages and production notes provide honest reference points for what survived the process.",
          ],
          table: { title: "FourFeetz scene approval order", headers: ["Stage", "Question", "If it fails"], rows: [["Reference", "Are character identity and scale readable?", "Replace or reframe the First Shot"], ["Action", "Can one movement finish cleanly?", "Simplify the action"], ["Continuity", "Do background and screen direction connect?", "Revise the shot or use a clear cut"], ["Edit", "Does the clip serve the scene purpose?", "Do not publish it"]] },
        },
      ],
      faqs: [
        { question: "Does FourFeetz publish its First Shot prompts?", answer: "No. We share the review method and finished evidence, but character-specific master prompts and internal reference systems remain private." },
        { question: "Why choose only one action?", answer: "One action makes anatomy, identity and continuity easier to inspect and leaves a cleaner end frame for the edit." },
      ],
      related: [
        { label: "Watch the Short", title: "A Quiet Rainy Evening with HARU & LUNA", href: "/shorts/haru-luna-quiet-rainy-evening" },
        { label: "Related Characters", title: "Meet HARU", href: "/characters/haru" },
        { label: "Related Production Story", title: "HARU & LUNA Rainy Window Video", href: "/insights/haru-luna-rainy-window-ai-pet-video" },
      ],
    },
    ko: {
      ...koreanShared,
      slug: "from-first-image-to-final-short",
      eyebrow: "FourFeetz 장면 기획",
      title: "첫 이미지에서 완성 쇼츠까지: FourFeetz가 캐릭터 장면을 기획하는 방법",
      shortTitle: "첫 이미지에서 완성 쇼츠까지",
      description: "기준 이미지 선택, 장면 목적과 한 가지 행동 정의, 구도 보호, 승인된 결과를 완성 쇼츠로 편집하는 실제 FourFeetz 장면 기획 과정을 소개합니다.",
      hero: "/images/insights/studio-workflow/first-image-to-final-short-board.png",
      heroAlt: "비 오는 창가 First Shot, 장면 계획과 완성 쇼츠를 연결한 FourFeetz 3단계 제작 보드",
      heroCaption: "승인된 First Shot에서 한 가지 행동의 장면 계획, 완성 세로 쇼츠로 이어지는 공개 제작 흐름을 표현한 편집형 보드이며 비공개 프롬프트나 설정은 표시하지 않았습니다.",
      heroPosition: "50% 50%",
      readTime: "약 8분",
      verdict: "FourFeetz는 장면 목적에서 거꾸로 쇼츠를 기획합니다. 승인된 기준 이미지로 외형과 구도를 정하고, 한 가지 행동으로 움직임을 검토한 뒤, 실제 편집 안에서 사용할 가치가 있는지 판단합니다.",
      tags: ["장면 기획", "First Shot", "AI 쇼츠", "캐릭터 일관성"],
      keywords: ["동물 캐릭터 장면 기획", "First Shot 제작 과정", "FourFeetz 쇼츠", "AI 캐릭터 연속성"],
      tools: ["Google Flow", "CapCut"],
      characters: ["HARU", "LUNA"],
      sections: [
        { id: "what-we-tested", title: "실제로 테스트한 것: 움직임보다 장면 목적 먼저 정하기", paragraphs: ["공개된 HARU와 LUNA의 비 오는 창가 쇼츠는 화려한 움직임이 아니라 두 캐릭터가 함께 보내는 조용한 순간에서 시작했습니다. 두 캐릭터를 소개하고, 비는 창밖에만 유지하며, 오리지널 음악이 들어갈 여백을 남겨야 했습니다. 이 목적이 영상 생성 전에 기준 프레임, 카메라 거리와 세로 구도를 결정했습니다.", "승인된 캐릭터 이미지나 실제 시퀀스 프레임을 눈으로 확인할 수 있는 근거로 사용합니다. 이 쇼츠에서는 휴대폰 크기에서도 HARU와 LUNA가 함께 읽혀야 했습니다. 두 캐릭터의 상대적 크기, 얼굴 방향, 창문의 위치, 귀와 발 주변 여백을 확인했습니다. 완성 프롬프트와 내부 레퍼런스 체계는 공개하지 않지만 판단 과정은 공유합니다."], images: [{ src: "/images/insights/haru-luna-rainy-window-01-opening.webp", alt: "비 오는 창가에서 쉬는 HARU와 LUNA의 오프닝 프레임", caption: "실제 오프닝 프레임이 두 캐릭터, 창문의 경계와 장면의 조용한 목적을 정합니다.", aspect: "video" }] },
        { id: "what-went-wrong", title: "문제가 생긴 방식: 한 샷에 전체 이야기를 맡기기", paragraphs: ["짧은 샷 하나에 공간 소개, 두 동물의 움직임, 표정 변화와 카메라 이동까지 함께 요구하면 여러 요소가 동시에 흔들릴 수 있습니다. 서로 달라야 할 반응이 기계적으로 맞춰지고, 발이 바닥에서 뜨거나, 비 오는 창이 다른 배경으로 재구성될 수 있습니다. 보기 좋은 결과라도 장면 연결을 약하게 만들면 사용하지 않습니다.", "기준 이미지를 단지 가장 예쁘다는 이유로 고르지 않습니다. 클로즈업은 얼굴을 지킬 수 있지만 행동 공간이 없고, 와이드 숏은 환경을 보여주지만 이름표나 표정이 보이지 않을 수 있습니다. 올바른 First Shot은 최종 편집을 지지하는 이미지입니다."], bullets: ["한 가지 장면 목적", "한 가지 주요 행동", "유지할 수 있는 카메라 위치", "귀와 발, 세로 안전 영역을 위한 여백"] },
        { id: "what-worked", title: "효과가 있었던 방법: 기준 이미지, 한 가지 행동, 편집 순서", paragraphs: ["FourFeetz는 기준 이미지 승인, 장면 목적, 관찰 가능한 한 가지 행동, 움직임 검토, 최종 편집 순서로 작업합니다. 비 오는 창가 쇼츠에서는 절제된 시선과 작은 자세 변화로 두 캐릭터의 반응 시간을 다르게 만들었습니다. 생성된 클립은 따로 보지 않고 앞뒤 장면 사이에서 판단했습니다.", "CapCut에서는 사용할 구간 선택, 시작과 끝 자르기, 장면 배열과 오리지널 음악 균형을 조정했습니다. 편집은 리듬과 유효한 전환을 다듬을 수 있지만 달라진 얼굴, 사라진 발이나 깨진 창문 구조를 복구할 수는 없습니다. 구조적인 문제가 있는 클립은 마무리 단계로 보내지 않습니다."], steps: ["검증된 캐릭터 또는 시퀀스 기준 이미지를 고릅니다.", "장면의 감정적 목적을 한 문장으로 씁니다.", "한 가지 주요 행동과 분명한 끝 자세를 정합니다.", "시작·중간·마지막 프레임을 기준 이미지와 비교합니다.", "승인된 결과만 실제 세로 편집에 배치합니다."], videos: [{ src: "/videos/shorts/haru-luna/haru-luna-rainy-evening-vertical-v2.mp4", poster: "/images/shorts/haru-luna/haru-luna-rainy-evening-vertical-v2-poster.webp", title: "HARU와 LUNA의 조용한 비 오는 저녁", caption: "장면 순서, 절제된 반응 시간과 최종 세로 구도를 확인한 FourFeetz 완성 쇼츠입니다.", presentation: "portrait" }] },
        { id: "practical-takeaway", title: "실전 핵심 정리: 편집에 필요한 장면을 승인하기", paragraphs: ["First Shot은 시네마틱하게 보인다고 완성되는 것이 아닙니다. 캐릭터를 보호하고, 계획한 행동이 물리적으로 가능하며, 이웃 장면과 연결될 때 제작 기준을 통과합니다. 전체 해상도와 휴대폰 크기에서 서로 다른 문제가 보이므로 두 크기로 모두 확인합니다.", "장면 목적을 정하고, 반드시 보여야 할 외형 요소를 표시하고, 행동을 제한한 뒤, 최종 화면 비율 안에서 결과를 시험해 보세요. 완성 쇼츠와 캐릭터 페이지, 제작 노트는 실제로 제작 과정을 통과한 결과를 확인할 수 있는 근거입니다."], table: { title: "FourFeetz 장면 승인 순서", headers: ["단계", "검토 질문", "실패할 때"], rows: [["기준 이미지", "캐릭터 외형과 크기가 읽히는가?", "First Shot 교체 또는 재구성"], ["행동", "한 가지 움직임이 깔끔하게 끝나는가?", "행동 단순화"], ["연속성", "배경과 화면 방향이 이어지는가?", "샷 수정 또는 명확한 컷"], ["편집", "클립이 장면 목적에 기여하는가?", "공개하지 않음"]] } },
      ],
      faqs: [{ question: "FourFeetz는 First Shot 프롬프트를 공개하나요?", answer: "아니요. 검토 방법과 완성 결과는 공유하지만 캐릭터별 마스터 프롬프트와 내부 레퍼런스 체계는 비공개로 관리합니다." }, { question: "왜 한 가지 행동만 선택하나요?", answer: "한 가지 행동은 해부학, 정체성과 장면 연결을 확인하기 쉽고 편집에 필요한 깨끗한 마지막 프레임을 남깁니다." }],
      related: [{ label: "완성 쇼츠", title: "HARU와 LUNA의 조용한 비 오는 저녁", href: "/ko/shorts/haru-luna-quiet-rainy-evening" }, { label: "관련 캐릭터", title: "HARU 만나기", href: "/ko/characters/haru" }, { label: "관련 제작기", title: "HARU와 LUNA 비 오는 창가 영상 제작기", href: "/ko/insights/haru-luna-rainy-window-ai-pet-video" }],
    },
  },
  "animal-character-short-publishing-checklist": {
    en: {
      ...shared, slug: "animal-character-short-publishing-checklist", eyebrow: "FourFeetz Quality Review", title: "What We Check Before Publishing an Animal Character Short", shortTitle: "Our Animal Character Short Publishing Check", description: "The practical face, limb, accessory, background, camera and edit-continuity checks FourFeetz uses before an animal character short is published.", hero: "/images/insights/studio-workflow/publishing-checklist-review-sheet.png", heroAlt: "Editorial animal-short review sheet with frame tiles and callouts for faces, paws, name tags, backgrounds, cameras and edit joins", heroCaption: "A public-facing review sheet visualizing the checks applied to animal-character frames before publication, without exposing prompts, settings or a private character bible.", readTime: "9 min read", verdict: "A clip is publishable only when character identity, animal anatomy, environment and edit continuity survive normal playback and frame review. A polished effect never overrides a broken face, limb or scene connection.", tags: ["Quality Review", "Publishing", "Animal Animation", "AI Shorts"], keywords: ["AI short publishing checklist", "animal character quality review", "AI video anatomy check", "FourFeetz production review"], tools: ["CapCut"], characters: ["OLI", "HARU", "RURU"],
      sections: [
        { id: "what-we-tested", title: "What We Tested: Review at Three Speeds", paragraphs: ["FourFeetz reviews a candidate at normal speed for story and rhythm, without sound for visual continuity, and frame by frame around difficult movement or joins. The OLI swimming short made this especially useful because water can hide a leg for a moment while also creating believable reflections and contact. Watching only at normal speed can miss a changing paw; studying only still frames can reject motion that reads naturally in playback.", "We compare the clip with the approved character page or First Shot. The checklist covers face and apparent age, ears, visible legs and paws, tail, collar or name tag, body-to-ground or body-to-water contact, background geometry, light direction, camera speed and the physical connection to adjacent scenes."], images: [{ src: "/images/insights/production/oli-backstroke-test.png", alt: "OLI backstroke production frame used to inspect body shape, legs and water contact", caption: "A real OLI production frame makes limb placement and water contact reviewable rather than abstract.", aspect: "video" }] },
        { id: "what-went-wrong", title: "What Went Wrong: Accepting a Strong Moment With a Hidden Failure", paragraphs: ["An expressive face or attractive camera move can pull attention away from a missing paw, duplicated leg or accessory that changes position. The error often becomes more visible after a loop, a crop or a neighboring shot is added. FourFeetz therefore does not approve a clip from its best frame; the complete usable range has to pass.", "Backgrounds are checked as physical spaces. Window frames, creek banks, furniture edges and horizon lines should not bend or jump without a story reason. A moving camera also has to remain motivated. Fast motion that merely hides identity drift is a rejection reason, not a finishing technique."], bullets: ["Face, muzzle, eye spacing and apparent age", "All visible legs, paws, ears and tail", "Collar, scarf or name-tag position", "Ground or water contact", "Background lines, light and camera direction", "Start and end frames at every edit join"] },
        { id: "what-worked", title: "What Worked: Fix the Smallest Failing Layer", paragraphs: ["When the problem is in a short removable range, the usable portion can be trimmed. When two valid scenes need a gentle passage, a short dissolve may support the transition. When the face, anatomy or background is structurally wrong through the shot, FourFeetz replaces the source clip or leaves it unpublished. Editing is not used to disguise a failed character.", "The decision is written in physical language: left rear paw disappears during the turn, name tag moves to the wrong side, creek edge jumps at the cut. A specific note points to a specific repair and prevents a vague request for more quality."], table: { title: "Use, revise or reject", headers: ["Finding", "Decision", "Reason"], rows: [["Minor unusable frames at an edge", "Trim", "The valid action remains complete"], ["Two valid calm scenes with a time shift", "Edit or short dissolve", "The transition is intentional"], ["Face or limb changes through the action", "Replace", "Identity or anatomy is structurally unstable"], ["No clean range or story purpose", "Do not publish", "Finishing cannot create missing value"]] } },
        { id: "practical-takeaway", title: "Practical Takeaway: Check the Viewer’s Experience, Then the Evidence", paragraphs: ["Start at normal speed because the finished story is the product. Then remove sound and inspect difficult frames because music can make a weak transition feel smoother than it is. Finally, view the exported file at phone size to confirm that expressions, tags and important action remain readable after platform framing.", "The checklist is intentionally public and reusable. It explains what FourFeetz inspects without revealing a character bible, private weighting or generation settings. The OLI, HARU and RURU pages let visitors compare the published character identity with finished shorts."], videos: [{ src: "/videos/shorts/oli/oli-peaceful-swim.mp4", poster: "/images/shorts/oli/oli-peaceful-swim-poster.png", title: "OLI’s Peaceful Swim", caption: "The published vertical short used as the finished evidence for the checks described in this article.", presentation: "portrait" }] },
      ], faqs: [{ question: "Can editing fix a wrong face or missing limb?", answer: "No. Trimming can remove a brief bad edge, but a structural identity or anatomy problem requires a replacement clip or a decision not to publish." }, { question: "Why review without sound?", answer: "Music and ambience can make a visual join feel smoother, so silent review exposes camera, background and character discontinuities." }], related: [{ label: "Watch the Short", title: "OLI’s Peaceful Swim", href: "/shorts/oli-peaceful-swim" }, { label: "Related Character", title: "Meet OLI", href: "/characters/oli" }, { label: "Related Guide", title: "What We Learned From OLI’s Swimming Scene", href: "/insights/oli-swimming-scene-lessons" }],
    },
    ko: {
      ...koreanShared, slug: "animal-character-short-publishing-checklist", eyebrow: "FourFeetz 품질 검수", title: "동물 캐릭터 쇼츠를 공개하기 전에 확인하는 것", shortTitle: "동물 캐릭터 쇼츠 공개 전 검수", description: "동물 캐릭터 쇼츠를 공개하기 전에 FourFeetz가 얼굴, 다리, 발, 장식, 배경, 카메라와 장면 연결을 확인하는 실제 검수 기준입니다.", hero: "/images/insights/studio-workflow/publishing-checklist-review-sheet.png", heroAlt: "얼굴, 발, 이름표, 배경, 카메라와 편집 연결을 작은 프레임과 표시로 점검하는 동물 쇼츠 검수 시트", heroCaption: "프롬프트, 설정이나 비공개 캐릭터 바이블을 노출하지 않고 공개 전 동물 캐릭터 프레임의 검수 항목을 표현한 편집형 시트입니다.", readTime: "약 9분", verdict: "캐릭터 정체성, 동물의 신체, 환경과 장면 연결이 일반 재생과 프레임 검토를 모두 통과해야 공개할 수 있습니다. 화려한 효과가 깨진 얼굴, 다리나 장면 연결보다 우선하지 않습니다.", tags: ["품질 검수", "공개", "동물 애니메이션", "AI 쇼츠"], keywords: ["AI 쇼츠 공개 체크리스트", "동물 캐릭터 품질 검수", "AI 영상 신체 검토", "FourFeetz 제작 검수"], tools: ["CapCut"], characters: ["OLI", "HARU", "RURU"],
      sections: [
        { id: "what-we-tested", title: "실제로 테스트한 것: 세 가지 속도로 검토하기", paragraphs: ["FourFeetz는 후보 영상을 정상 속도에서 이야기와 리듬으로 보고, 소리 없이 시각적 연결을 확인하며, 어려운 움직임이나 접합부를 프레임 단위로 봅니다. OLI 수영 쇼츠에서는 물이 다리를 잠시 가리는 동시에 반사와 접촉을 만들기 때문에 이 방식이 특히 유용했습니다. 정상 속도만 보면 변하는 발을 놓칠 수 있고, 정지 프레임만 보면 자연스럽게 읽히는 움직임을 잘못 거절할 수 있습니다.", "승인된 캐릭터 페이지 또는 First Shot과 비교합니다. 얼굴과 나이 인상, 귀, 보이는 다리와 발, 꼬리, 목걸이나 이름표, 바닥 또는 물과 몸의 접촉, 배경 구조, 빛 방향, 카메라 속도와 앞뒤 장면의 물리적 연결을 확인합니다."], images: [{ src: "/images/insights/production/oli-backstroke-test.png", alt: "몸 형태, 다리와 물 접촉을 확인한 OLI 배영 제작 프레임", caption: "실제 OLI 제작 프레임은 다리 위치와 물 접촉을 구체적으로 검토하게 해 줍니다.", aspect: "video" }] },
        { id: "what-went-wrong", title: "문제가 생긴 방식: 좋은 순간 때문에 숨은 오류를 승인하기", paragraphs: ["표정이 좋거나 카메라 움직임이 매력적이면 사라진 발, 중복된 다리나 위치가 바뀐 이름표를 놓칠 수 있습니다. 이 오류는 반복, 크롭 또는 이웃 장면을 붙인 뒤 더 잘 보입니다. 가장 좋은 한 프레임만 보고 승인하지 않고 실제 사용할 전체 구간을 확인합니다.", "배경도 물리적 공간으로 봅니다. 창틀, 개울 둑, 가구 모서리와 수평선이 이유 없이 휘거나 뛰지 않아야 합니다. 빠른 카메라가 정체성 흔들림을 숨길 뿐이라면 마무리 기법이 아니라 거절 사유입니다."], bullets: ["얼굴, 주둥이, 눈 간격과 나이 인상", "보이는 모든 다리, 발, 귀와 꼬리", "목걸이, 스카프 또는 이름표 위치", "바닥 또는 물과의 접촉", "배경선, 빛과 카메라 방향", "모든 편집 접합부의 시작과 끝 프레임"] },
        { id: "what-worked", title: "효과가 있었던 방법: 가장 작은 실패 층을 고치기", paragraphs: ["문제가 짧은 가장자리 구간에만 있으면 사용할 수 있는 부분을 자릅니다. 유효한 두 장면 사이에 부드러운 시간 경과가 필요하면 짧은 디졸브를 사용할 수 있습니다. 얼굴, 신체 또는 배경이 샷 전체에서 구조적으로 잘못되면 원본 클립을 교체하거나 공개하지 않습니다. 편집으로 실패한 캐릭터를 감추지 않습니다.", "수정 메모는 왼쪽 뒷발이 회전 중 사라짐, 이름표가 반대편으로 이동, 컷에서 개울 가장자리가 뜀처럼 물리적인 언어로 씁니다. 구체적인 메모가 구체적인 수정으로 이어집니다."], table: { title: "사용·수정·제외 기준", headers: ["발견", "판단", "이유"], rows: [["가장자리의 짧은 불량 프레임", "자르기", "유효한 행동이 완결됨"], ["시간이 바뀌는 유효한 두 장면", "편집 또는 짧은 디졸브", "의도된 전환"], ["행동 중 얼굴이나 다리 변화", "교체", "정체성 또는 신체가 불안정"], ["깨끗한 구간이나 장면 목적 없음", "공개하지 않음", "마무리로 가치를 만들 수 없음"]] } },
        { id: "practical-takeaway", title: "실전 핵심 정리: 시청 경험을 보고 근거를 확인하기", paragraphs: ["완성된 이야기가 제품이므로 정상 속도에서 시작합니다. 음악이 약한 전환을 부드럽게 느끼게 할 수 있으므로 소리를 제거하고 어려운 프레임을 확인합니다. 마지막으로 내보낸 파일을 휴대폰 크기로 보며 플랫폼 화면에서도 표정, 이름표와 주요 행동이 읽히는지 확인합니다.", "이 체크리스트는 재사용할 수 있는 공개 원칙입니다. 캐릭터 바이블이나 내부 가중치, 생성 설정을 공개하지 않으면서 무엇을 검토하는지 설명합니다. OLI, HARU와 RURU 페이지에서 공개된 정체성과 완성 쇼츠를 비교할 수 있습니다."], videos: [{ src: "/videos/shorts/oli/oli-peaceful-swim.mp4", poster: "/images/shorts/oli/oli-peaceful-swim-poster.png", title: "OLI의 평화로운 수영", caption: "이 글의 검수 기준을 통과한 완성 근거인 공개 세로 쇼츠입니다.", presentation: "portrait" }] },
      ], faqs: [{ question: "편집으로 잘못된 얼굴이나 사라진 다리를 고칠 수 있나요?", answer: "아니요. 가장자리의 짧은 오류는 잘라낼 수 있지만 구조적인 정체성이나 신체 문제는 클립을 교체하거나 공개하지 않아야 합니다." }, { question: "왜 소리 없이 검토하나요?", answer: "음악과 앰비언스가 시각적 연결을 더 부드럽게 느끼게 할 수 있어 무음 검토로 카메라, 배경과 캐릭터의 불연속을 찾습니다." }], related: [{ label: "완성 쇼츠", title: "OLI의 평화로운 수영", href: "/ko/shorts/oli-peaceful-swim" }, { label: "관련 캐릭터", title: "OLI 만나기", href: "/ko/characters/oli" }, { label: "관련 가이드", title: "OLI 수영 장면에서 배운 것", href: "/ko/insights/oli-swimming-scene-lessons" }],
    },
  },
  "why-we-keep-animal-motions-simple": {
    en: {
      ...shared, slug: "why-we-keep-animal-motions-simple", eyebrow: "FourFeetz Motion Direction", title: "Why We Keep Some Animal Motions Simple", shortTitle: "Why We Keep Animal Motions Simple", description: "What HARU, OLI and MILO production tests taught FourFeetz about fast running, complex full-body action, camera movement and choosing stable animal performance.", hero: "/images/insights/studio-workflow/simple-motion-fixed-camera-oli.png", heroAlt: "OLI holding a stable seated pose inside fixed-camera frame marks with faint echoes of one small head turn", heroCaption: "A fixed-camera editorial scene uses OLI’s planted paws and a restrained head turn to show why one reviewable motion can be stronger than complex full-body action.", readTime: "8 min read", verdict: "Simple motion is a directing choice, not a lack of ambition. It keeps paws, ground contact, silhouette and character temperament reviewable, especially when a short scene must connect cleanly to the next one.", tags: ["Animal Motion", "Character Animation", "AI Video", "Motion Direction"], keywords: ["simple animal motion AI video", "animal character animation problems", "AI running motion", "FourFeetz motion direction"], tools: ["Google Flow", "Runway", "Kling AI"], characters: ["HARU", "OLI", "MILO"],
      sections: [
        { id: "what-we-tested", title: "What We Tested: Full-Body Action Across Different Animals", paragraphs: ["FourFeetz has published quiet walking, resting, swimming and playful character moments across different body types. HARU’s compact puppy proportions, OLI’s long flexible body and MILO’s energetic silhouette do not create the same motion problem. We tested action by asking what has to remain readable: paws and ground contact for a puppy, legs and water contact for an otter, or body scale and foot placement for a larger upbeat character.", "Fast running and complicated turns ask a short generation to solve limb cycles, weight transfer, facial identity, background travel and often camera tracking at the same time. An individual frame can look convincing while the body changes between frames. The problem becomes clearer when the result is slowed, looped or placed next to an approved First Shot."], images: [{ src: "/images/insights/production/oli-creek-first-shot.png", alt: "OLI standing beside a creek before a simple swimming action", caption: "A stable real production frame gives OLI room for one readable action and keeps the creek geometry visible.", aspect: "video" }, { src: "/images/characters/milo/portrait.png", alt: "Approved MILO portrait showing the character silhouette and proportions", caption: "MILO’s approved portrait provides the silhouette and scale evidence that motion still has to preserve.", fit: "contain" }] },
        { id: "what-went-wrong", title: "What Went Wrong: Speed Hid Anatomy Until the Edit", paragraphs: ["In complex full-body tests, legs can cross, merge or change length while the torso stretches to complete the action. Water may hide part of OLI and make the first viewing feel plausible, but the body shape or paw placement can still fail at the surface. For a running animal, camera tracking can also change the apparent size and make a cut to the next scene difficult.", "Adding more movement instructions did not make the action more controlled. It created more destinations. A character can run, turn, look at camera and jump only if every transition is solved; a short generation may instead blend those actions. FourFeetz rejects a take when anatomy, temperament or the planned edit becomes unclear."], bullets: ["Merged or changing legs during a fast cycle", "Paws sliding instead of carrying weight", "Body length or scale changing through a turn", "Camera speed hiding identity drift", "An end pose that cannot connect to the next shot"] },
        { id: "what-worked", title: "What Worked: One Observable Action in a Stable Frame", paragraphs: ["HARU’s quiet scenes use breathing, a glance, a careful step or one yawn because those actions fit his gentle temperament and leave the face readable. OLI’s calmer swim works when the body direction and water contact stay clear. For MILO, an upbeat pose can be communicated through posture and a small weight shift before asking for a complex run.", "We choose the lowest motion complexity that communicates the story beat. The camera is kept static or given one restrained move, and the action receives a clear end state. This makes comparison honest: if a paw or silhouette changes, the error cannot be excused as intentional speed."], table: { title: "Motion choice by production risk", headers: ["Story need", "Stable starting choice", "Review focus"], rows: [["Quiet HARU beat", "Breathing, glance or one step", "Face, scarf/collar and paw contact"], ["OLI in water", "One swim direction or float", "Body length, legs and surface contact"], ["Energetic MILO beat", "Pose change or short weight shift", "Scale, silhouette and feet"], ["Fast travel", "Separate shorter shots", "End pose and screen direction"]] } },
        { id: "practical-takeaway", title: "Practical Takeaway: Complexity Must Earn Its Place", paragraphs: ["Simple motion should not mean lifeless motion. Small breathing, blinking, fur response, water movement and environmental motion can keep a frame alive while the primary action remains readable. The goal is to give the audience one clear behavior, not to display every movement the tool can attempt.", "Increase complexity only after the character, camera and environment survive the simpler version. If fast travel is essential, divide it into shorter purposeful shots with usable beginning and end poses. The finished OLI short and HARU relaxing films show what this restraint looks like after editing."], videos: [{ src: "/videos/shorts/oli/oli-peaceful-swim.mp4", poster: "/images/shorts/oli/oli-peaceful-swim-poster.png", title: "OLI’s Peaceful Swim", caption: "A finished example of one calm animal action carrying the scene without an unnecessary camera performance.", presentation: "portrait" }] },
      ], faqs: [{ question: "Does simple motion mean a static image?", answer: "No. Supporting motion such as breathing, blinking, water or fire can remain active while one primary character action stays clear." }, { question: "When should a fast action be used?", answer: "When it is necessary to the story and the character, anatomy, camera and edit points remain stable in controlled tests." }], related: [{ label: "Watch the Short", title: "OLI’s Peaceful Swim", href: "/shorts/oli-peaceful-swim" }, { label: "Related Characters", title: "Meet MILO", href: "/characters/milo" }, { label: "Related Guide", title: "Character Consistency Across HARU, RURU and MILO", href: "/insights/character-consistency-haru-ruru-milo" }],
    },
    ko: {
      ...koreanShared, slug: "why-we-keep-animal-motions-simple", eyebrow: "FourFeetz 움직임 연출", title: "일부 동물 캐릭터의 움직임을 단순하게 유지하는 이유", shortTitle: "동물 캐릭터 움직임을 단순하게 만드는 이유", description: "HARU, OLI와 MILO 제작에서 빠른 달리기, 복잡한 전신 행동과 카메라 움직임을 테스트하며 안정적인 동작을 선택한 이유입니다.", hero: "/images/insights/studio-workflow/simple-motion-fixed-camera-oli.png", heroAlt: "고정 카메라 프레임 안에서 발을 안정적으로 두고 작은 머리 움직임만 보여주는 OLI", heroCaption: "OLI의 접지된 발과 절제된 머리 움직임을 통해 복잡한 전신 행동보다 검토 가능한 한 가지 동작을 선택하는 의미를 표현했습니다.", readTime: "약 8분", verdict: "단순한 움직임은 야심이 부족해서가 아니라 연출 선택입니다. 특히 짧은 장면을 다음 장면과 연결해야 할 때 발, 접지, 실루엣과 캐릭터의 성격을 검토할 수 있게 합니다.", tags: ["동물 움직임", "캐릭터 애니메이션", "AI 영상", "움직임 연출"], keywords: ["단순한 동물 움직임 AI 영상", "동물 캐릭터 애니메이션 문제", "AI 달리기 움직임", "FourFeetz 움직임 연출"], tools: ["Google Flow", "Runway", "Kling AI"], characters: ["HARU", "OLI", "MILO"],
      sections: [
        { id: "what-we-tested", title: "실제로 테스트한 것: 서로 다른 동물의 전신 행동", paragraphs: ["FourFeetz는 서로 다른 체형으로 조용한 걷기, 휴식, 수영과 장난스러운 순간을 공개했습니다. HARU의 작은 강아지 비율, OLI의 길고 유연한 몸, MILO의 활기찬 실루엣은 같은 움직임 문제를 만들지 않습니다. 강아지는 발과 접지, 수달은 다리와 물 접촉, 더 크고 밝은 캐릭터는 몸의 크기와 발 위치처럼 반드시 읽혀야 할 요소를 먼저 정합니다.", "빠른 달리기와 복잡한 회전은 짧은 생성 안에서 다리 주기, 체중 이동, 얼굴 정체성, 배경 이동과 카메라 추적을 동시에 해결하도록 요구합니다. 한 프레임은 그럴듯해도 프레임 사이에서 몸이 바뀔 수 있습니다. 느리게 보거나 반복하고 승인된 First Shot 옆에 두면 문제가 더 분명해집니다."], images: [{ src: "/images/insights/production/oli-creek-first-shot.png", alt: "단순한 수영 행동 전에 개울가에 서 있는 OLI", caption: "안정된 실제 제작 프레임이 OLI에게 한 가지 행동 공간을 주고 개울 구조를 확인하게 합니다.", aspect: "video" }, { src: "/images/characters/milo/portrait.png", alt: "MILO의 실루엣과 비율을 보여주는 승인된 캐릭터 초상", caption: "MILO의 승인된 초상은 움직임에서도 지켜야 할 실루엣과 크기 근거입니다.", fit: "contain" }] },
        { id: "what-went-wrong", title: "문제가 생긴 방식: 편집 전까지 속도가 신체 오류를 숨기기", paragraphs: ["복잡한 전신 테스트에서는 다리가 교차·합쳐지거나 길이가 바뀌고, 몸통이 행동을 완성하려고 늘어날 수 있습니다. 물이 OLI의 일부를 가리면 첫 시청은 그럴듯하지만 수면에서 몸 형태나 발 위치가 실패할 수 있습니다. 달리는 동물을 추적하는 카메라는 크기 인상을 바꾸고 다음 장면과의 컷을 어렵게 만들기도 합니다.", "움직임 지시를 더 많이 추가해도 행동이 통제되지는 않았습니다. 도착점만 늘어났습니다. 달리기, 회전, 카메라 보기와 점프의 모든 전환이 해결되지 않으면 행동이 섞입니다. 신체, 성격이나 편집 계획이 불분명한 결과는 사용하지 않습니다."], bullets: ["빠른 주기에서 합쳐지거나 변하는 다리", "체중을 싣지 못하고 미끄러지는 발", "회전 중 달라지는 몸 길이와 크기", "정체성 흔들림을 숨기는 카메라 속도", "다음 샷과 연결할 수 없는 끝 자세"] },
        { id: "what-worked", title: "효과가 있었던 방법: 안정된 프레임 안의 한 가지 행동", paragraphs: ["HARU의 조용한 장면은 호흡, 시선, 조심스러운 한 걸음이나 한 번의 하품을 사용합니다. 부드러운 성격에 맞고 얼굴을 볼 수 있기 때문입니다. OLI는 몸 방향과 물 접촉이 분명할 때 차분한 수영이 안정됩니다. MILO는 복잡한 달리기 전에 자세와 작은 체중 이동만으로 활기찬 느낌을 전달할 수 있습니다.", "이야기 장면을 전달하는 가장 낮은 움직임 복잡도를 고릅니다. 카메라는 고정하거나 한 가지 절제된 움직임만 주고, 행동에는 분명한 끝 자세를 둡니다. 발이나 실루엣이 변하면 속도 때문이라고 넘기지 않고 오류를 확인할 수 있습니다."], table: { title: "제작 위험에 따른 움직임 선택", headers: ["이야기 필요", "안정적인 시작 선택", "검토 초점"], rows: [["조용한 HARU 장면", "호흡, 시선 또는 한 걸음", "얼굴, 스카프/목걸이와 발 접촉"], ["물속 OLI", "한 방향 수영 또는 떠 있기", "몸 길이, 다리와 수면 접촉"], ["활기찬 MILO 장면", "자세 변화 또는 짧은 체중 이동", "크기, 실루엣과 발"], ["빠른 이동", "더 짧은 별도 샷", "끝 자세와 화면 방향"]] } },
        { id: "practical-takeaway", title: "실전 핵심 정리: 복잡함에는 이유가 있어야 합니다", paragraphs: ["단순한 움직임은 정지 이미지를 뜻하지 않습니다. 작은 호흡, 눈 깜빡임, 털 반응, 물과 환경 움직임으로 프레임을 살아 있게 하면서 주요 행동은 읽히게 할 수 있습니다. 도구가 시도할 수 있는 모든 움직임을 보여주는 것이 아니라 관객에게 한 가지 분명한 행동을 전달하는 것이 목적입니다.", "더 단순한 버전에서 캐릭터, 카메라와 환경이 유지된 뒤에만 복잡도를 높이세요. 빠른 이동이 꼭 필요하면 사용할 수 있는 시작과 끝 자세를 가진 짧은 샷으로 나누세요. 완성된 OLI 쇼츠와 HARU 릴렉스 필름에서 이 절제를 확인할 수 있습니다."], videos: [{ src: "/videos/shorts/oli/oli-peaceful-swim.mp4", poster: "/images/shorts/oli/oli-peaceful-swim-poster.png", title: "OLI의 평화로운 수영", caption: "불필요한 카메라 연기 없이 한 가지 차분한 동물 행동으로 장면을 완성한 사례입니다.", presentation: "portrait" }] },
      ], faqs: [{ question: "단순한 움직임은 정지 이미지를 뜻하나요?", answer: "아니요. 한 가지 주요 행동을 분명하게 유지하면서 호흡, 눈 깜빡임, 물이나 불 같은 보조 움직임을 사용할 수 있습니다." }, { question: "빠른 행동은 언제 사용하나요?", answer: "이야기에 꼭 필요하고 통제된 테스트에서 캐릭터, 신체, 카메라와 편집 지점이 안정될 때 사용합니다." }], related: [{ label: "완성 쇼츠", title: "OLI의 평화로운 수영", href: "/ko/shorts/oli-peaceful-swim" }, { label: "관련 캐릭터", title: "MILO 만나기", href: "/ko/characters/milo" }, { label: "관련 가이드", title: "HARU·RURU·MILO 캐릭터 일관성", href: "/ko/insights/character-consistency-haru-ruru-milo" }],
    },
  },
  "turning-short-scene-into-relaxing-video": {
    en: {
      ...shared, slug: "turning-short-scene-into-relaxing-video", eyebrow: "FourFeetz Relax Moments", title: "Turning a Short Scene Into a Relaxing Video", shortTitle: "Turning a Short Scene Into a Relaxing Video", description: "How FourFeetz shaped a short HARU fireplace scene into a four-minute relaxing video using restrained motion, clean loop points, CapCut edits and original sound.", hero: "/images/insights/studio-workflow/relaxing-video-loop-board.png", heroAlt: "Curved strip of calm puppy scene frames connected by a loop arrow, soft dissolve overlays and an ambience waveform", heroCaption: "A handcrafted scene strip visualizes compatible resting frames, a short dissolve, a returning loop and continuous ambience without imitating an editing program interface.", readTime: "9 min read", verdict: "A relaxing video is not made by repeating any attractive clip. The source needs a stable pose and environment, the loop needs a physically plausible handoff, and sound must support the join without pretending to fix a visual failure.", tags: ["Relaxing Video", "Loop Editing", "CapCut", "HARU"], keywords: ["make relaxing AI video", "CapCut seamless loop", "HARU relaxing video", "short scene to long video"], tools: ["Google Flow", "CapCut", "Suno"], characters: ["HARU"],
      sections: [
        { id: "what-we-tested", title: "What We Tested: Separate the Opening Action From the Resting Loop", paragraphs: ["HARU — Snowy Hearth Nap is a published 4 minute 04 second FourFeetz Relax Moments film. Its production record separates one sleepy yawn and head-lowering action from the later resting loop. That division mattered: the yawn creates a small story beat, while restrained breathing can repeat without making HARU perform the same obvious event every few seconds.", "The approved First Shot fixed HARU’s visible age, collar, teddy bear, stone fireplace, closed winter window and warm light. The camera remained static. Snow was kept outside the closed window and fireplace motion stayed environmental, so the viewer could read the room as stable while HARU settled."], images: [{ src: "/images/works/haru-relax-moments-ep03/first-shot.webp", alt: "Approved First Shot of HARU awake beside a teddy bear and fireplace", caption: "The approved First Shot establishes every element that the opening action and later loop must preserve.", aspect: "video" }, { src: "/images/works/haru-relax-moments-ep03/final-sleeping-shot.webp", alt: "HARU sleeping beside the teddy bear in the final resting position", caption: "The final sleeping position is calmer and more repeatable than the visible yawn that leads into it.", aspect: "video" }] },
        { id: "what-went-wrong", title: "What Went Wrong: Repeating an Event Instead of a State", paragraphs: ["A visible action such as a yawn, standing up or moving an object has a beginning and an end. Repeating it makes time reset in a way the viewer notices. Larger pose changes also risk a different face, shifted collar, moving teddy bear or altered fireplace geometry at every join.", "A dissolve can soften small differences between compatible resting frames, but a long crossfade produces double eyes, doubled paws or a ghosted teddy bear. Audio can create a similar problem: a fireplace pop or strong musical accent at the loop boundary announces the restart even when the image is gentle."], bullets: ["Do not loop a story event as if it were a resting state.", "Do not use a dissolve to hide a changed face or object.", "Avoid distinctive sound events at the repeated boundary.", "Check the closed window mask so snow never appears inside the room."] },
        { id: "what-worked", title: "What Worked: Trim, Short Dissolve and Sound Support in CapCut", paragraphs: ["CapCut was used for loop assembly, trimming to compatible breathing phases, testing short dissolves, keeping snowfall confined to the window area, mixing the original music beneath fireplace ambience and exporting the final film. We chose the shortest overlap that softened a valid join without creating visible duplication.", "The edit could control timing, ordering, audio balance and the window composite. It could not repair a different HARU face, a collar jump or a changed teddy bear. A source clip with those failures was not promoted simply because a dissolve made the cut less obvious."], table: { title: "CapCut’s role and limit", headers: ["Task", "Useful for", "Not a fix for"], rows: [["Trim", "Finding compatible breathing phases", "Identity drift through the whole clip"], ["Short dissolve", "Softening a small valid pose difference", "Double eyes, paws or changed objects"], ["Sound mix", "Supporting calm and masking audio clicks", "A visible discontinuity"], ["Window mask", "Keeping snow outside", "Reconstructed room geometry"]] } },
        { id: "practical-takeaway", title: "Practical Takeaway: Build a Calm State That Can Continue", paragraphs: ["Plan an opening beat and a separate repeatable state. The loop state should contain controlled cyclical motion such as breathing, firelight or distant snowfall and should avoid moving props to new positions. Compare the first and last seconds at normal speed and frame by frame, then listen for clicks or musical accents at the join.", "The complete film is embedded below and linked from the FourFeetz video library. It is the result used to support these production notes; no viewing statistics or unverified performance claims are needed."], videos: [{ src: "/videos/films/haru-relax-moments-ep03/snowy-fireplace-nap.mp4", poster: "/images/works/haru-relax-moments-ep03/first-shot.webp", title: "HARU — Snowy Hearth Nap", caption: "The published 4:04 FourFeetz Relax Moments film assembled from an opening action, restrained resting loop, original music, ambience and winter window composite." }] },
      ], faqs: [{ question: "Can any short clip become a relaxing loop?", answer: "No. The clip needs a stable environment, compatible start and end states, and motion that can repeat without resetting a visible event." }, { question: "What did CapCut do in this production?", answer: "It handled trimming, loop assembly, short dissolve tests, window masking, sound mix and final delivery; it did not replace failed character or scene generation." }], related: [{ label: "Watch the Film", title: "HARU — Snowy Hearth Nap", href: "/works/haru-snowy-hearth-nap" }, { label: "All Videos", title: "FourFeetz Video Library", href: "/videos" }, { label: "Related Guide", title: "How We Keep HARU Relaxing Videos Calm", href: "/insights/haru-relaxing-videos-calm-natural" }],
    },
    ko: {
      ...koreanShared, slug: "turning-short-scene-into-relaxing-video", eyebrow: "FourFeetz Relax Moments", title: "짧은 장면을 릴렉스 영상으로 만드는 방법", shortTitle: "짧은 장면을 릴렉스 영상으로 만들기", description: "절제된 움직임, 깨끗한 반복 지점, CapCut 편집과 오리지널 사운드로 짧은 HARU 벽난로 장면을 4분대 릴렉스 영상으로 만든 과정입니다.", hero: "/images/insights/studio-workflow/relaxing-video-loop-board.png", heroAlt: "차분한 강아지 장면 스트립을 루프 화살표, 부드러운 디졸브 겹침과 앰비언스 파형으로 연결한 편집형 이미지", heroCaption: "실제 편집 프로그램 화면을 흉내 내지 않고 호환되는 휴식 프레임, 짧은 디졸브, 되돌아오는 루프와 이어지는 앰비언스를 장면 스트립으로 표현했습니다.", readTime: "약 9분", verdict: "보기 좋은 클립을 반복한다고 릴렉스 영상이 되지는 않습니다. 원본에 안정된 자세와 환경이 필요하고, 반복 지점은 물리적으로 이어져야 하며, 사운드는 시각적 실패를 감추지 않고 연결을 지지해야 합니다.", tags: ["릴렉스 영상", "루프 편집", "CapCut", "HARU"], keywords: ["AI 릴렉스 영상 만들기", "CapCut 자연스러운 루프", "HARU 릴렉스 영상", "짧은 장면 롱폼 영상"], tools: ["Google Flow", "CapCut", "Suno"], characters: ["HARU"],
      sections: [
        { id: "what-we-tested", title: "실제로 테스트한 것: 오프닝 행동과 휴식 루프 분리하기", paragraphs: ["HARU — Snowy Hearth Nap은 공개된 4분 04초 길이의 FourFeetz Relax Moments 영상입니다. 제작 기록에서는 졸린 하품과 머리를 내리는 한 가지 행동을 이후의 휴식 루프와 분리했습니다. 하품은 작은 이야기 장면을 만들지만 절제된 호흡은 몇 초마다 같은 사건을 다시 연기하지 않고 반복할 수 있습니다.", "승인된 First Shot에서 HARU의 나이 인상, 목걸이, 곰인형, 돌 벽난로, 닫힌 겨울 창문과 따뜻한 빛을 정했습니다. 카메라는 고정했습니다. 눈은 닫힌 창문 밖에만 두고 불꽃 움직임은 환경 요소로 유지해 HARU가 잠드는 동안 방이 안정된 공간으로 보이게 했습니다."], images: [{ src: "/images/works/haru-relax-moments-ep03/first-shot.webp", alt: "곰인형과 벽난로 옆에서 깨어 있는 HARU의 승인된 First Shot", caption: "승인된 First Shot이 오프닝 행동과 이후 반복에서 유지할 모든 요소를 정합니다.", aspect: "video" }, { src: "/images/works/haru-relax-moments-ep03/final-sleeping-shot.webp", alt: "마지막 휴식 자세로 곰인형 옆에서 잠든 HARU", caption: "마지막 수면 자세는 앞의 하품보다 차분하고 반복하기 쉽습니다.", aspect: "video" }] },
        { id: "what-went-wrong", title: "문제가 생긴 방식: 상태가 아니라 사건을 반복하기", paragraphs: ["하품, 일어서기 또는 물건 옮기기 같은 눈에 띄는 행동에는 시작과 끝이 있습니다. 반복하면 시간이 초기화되는 것이 보입니다. 큰 자세 변화는 접합부마다 얼굴, 목걸이, 곰인형 또는 벽난로 구조가 달라질 위험도 높입니다.", "디졸브는 호환되는 휴식 프레임의 작은 차이를 부드럽게 할 수 있지만 길게 겹치면 눈, 발이나 곰인형이 이중으로 보입니다. 벽난로의 강한 팝이나 반복 경계의 음악 악센트도 이미지가 부드러워도 재시작을 알려 줍니다."], bullets: ["이야기 사건을 휴식 상태처럼 반복하지 않습니다.", "달라진 얼굴이나 물체를 디졸브로 숨기지 않습니다.", "반복 경계에 뚜렷한 소리 사건을 피합니다.", "닫힌 창문 마스크를 확인해 실내에 눈이 나타나지 않게 합니다."] },
        { id: "what-worked", title: "효과가 있었던 방법: CapCut의 자르기·짧은 디졸브·사운드 보완", paragraphs: ["CapCut에서는 호환되는 호흡 단계에 맞춘 자르기, 루프 조립, 짧은 디졸브 테스트, 창문 영역에만 눈을 두는 마스킹, 벽난로 앰비언스 아래 오리지널 음악 믹스와 최종 내보내기를 진행했습니다. 눈에 띄는 중복 없이 유효한 연결을 부드럽게 하는 가장 짧은 겹침을 선택했습니다.", "편집은 타이밍, 순서, 오디오 균형과 창문 합성을 통제할 수 있습니다. 달라진 HARU 얼굴, 목걸이 점프나 바뀐 곰인형은 고칠 수 없습니다. 이런 문제가 있는 원본을 디졸브로 덜 보이게 했다는 이유로 사용하지 않았습니다."], table: { title: "CapCut의 역할과 한계", headers: ["작업", "도움이 되는 범위", "고칠 수 없는 것"], rows: [["자르기", "호환되는 호흡 단계 찾기", "클립 전체의 정체성 흔들림"], ["짧은 디졸브", "유효한 작은 자세 차이 완화", "이중 눈·발 또는 바뀐 물체"], ["사운드 믹스", "차분함과 오디오 클릭 보완", "눈에 보이는 불연속"], ["창문 마스크", "눈을 실외에 유지", "재구성된 방 구조"]] } },
        { id: "practical-takeaway", title: "실전 핵심 정리: 계속될 수 있는 차분한 상태 만들기", paragraphs: ["오프닝 장면과 별도의 반복 가능한 상태를 기획하세요. 루프 상태에는 호흡, 불빛이나 먼 눈처럼 통제된 순환 움직임을 두고 소품이 새 위치로 이동하지 않게 합니다. 처음과 마지막 몇 초를 정상 속도와 프레임 단위로 비교한 뒤 접합부의 클릭이나 음악 악센트를 들어봅니다.", "아래에 전체 영상을 직접 넣고 FourFeetz 영상 라이브러리와 연결했습니다. 이 제작 노트의 근거는 실제 완성 결과이며 조회 수나 확인할 수 없는 성과 주장은 사용하지 않습니다."], videos: [{ src: "/videos/films/haru-relax-moments-ep03/snowy-fireplace-nap.mp4", poster: "/images/works/haru-relax-moments-ep03/first-shot.webp", title: "HARU — Snowy Hearth Nap", caption: "오프닝 행동, 절제된 휴식 루프, 오리지널 음악, 앰비언스와 겨울 창문 합성으로 완성한 4분 04초 FourFeetz Relax Moments 영상입니다." }] },
      ], faqs: [{ question: "모든 짧은 클립을 릴렉스 루프로 만들 수 있나요?", answer: "아니요. 안정된 환경, 호환되는 시작과 끝 상태, 눈에 띄는 사건을 초기화하지 않고 반복할 수 있는 움직임이 필요합니다." }, { question: "이 제작에서 CapCut은 무엇을 했나요?", answer: "자르기, 루프 조립, 짧은 디졸브 테스트, 창문 마스킹, 사운드 믹스와 최종 전달을 담당했으며 실패한 캐릭터나 장면 생성을 대신하지 않았습니다." }], related: [{ label: "완성 영상", title: "HARU — Snowy Hearth Nap", href: "/ko/films/haru-snowy-hearth-nap" }, { label: "전체 영상", title: "FourFeetz 영상 라이브러리", href: "/ko/videos" }, { label: "관련 가이드", title: "HARU 릴렉스 영상을 차분하게 만드는 방법", href: "/ko/insights/haru-relaxing-videos-calm-natural" }],
    },
  },
  "what-we-keep-private-character-production": {
    en: {
      ...shared, slug: "what-we-keep-private-character-production", eyebrow: "FourFeetz Studio Policy", title: "What We Keep Private in Our Character Production Process", shortTitle: "What We Keep Private in Character Production", description: "Why FourFeetz keeps character master prompts and internal production assets private while sharing useful review principles, production evidence and finished results.", hero: "/images/insights/studio-workflow/private-character-studio-archive.png", heroAlt: "Walnut studio archive divided between public finished artwork and closed burgundy and green production folios", heroCaption: "Public presentation pieces remain visible while closed, blank archival folios represent protected studio materials; no prompt, setting or private document content appears.", readTime: "7 min read", verdict: "FourFeetz separates teachable production principles from proprietary character assets. Visitors can learn how to define a scene, review identity and judge a finished result without receiving the master prompts or internal systems that maintain the studio’s character IP.", tags: ["Character IP", "Production Policy", "Character Consistency", "Studio Practice"], keywords: ["private AI character prompts", "character IP production", "FourFeetz character assets", "responsible production sharing"], tools: [], characters: ["HARU", "OLI", "MILO"],
      sections: [
        { id: "what-we-tested", title: "What We Tested: What Actually Helps Another Creator", paragraphs: ["A complete character prompt may look like the most direct educational material, but it answers how to reproduce one protected design rather than how to make better production decisions. FourFeetz instead publishes real First Shots, finished videos, selected production frames, checklists and specific failure descriptions. These materials let a visitor see what the scene had to preserve and what survived the edit.", "The public HARU face and character images are used as visible examples of silhouette, age, coat, ears and expression. They do not include the complete internal character bible, master prompt, weighting logic, generation history or latest settings. The distinction lets the site remain useful without turning original character identity into a downloadable recipe."], images: [{ src: "/images/insights/haru-official-face-pack.png", alt: "Public HARU face reference showing consistent ears, eyes, muzzle and puppy proportions", caption: "A public-facing HARU reference can teach what to inspect while the complete internal production system remains private.", fit: "contain", aspect: "landscape" }] },
        { id: "what-went-wrong", title: "What Went Wrong: Confusing Transparency With Full Asset Release", paragraphs: ["Listing every setting can create false certainty because tools, models and interfaces change. It can also expose the exact combination used to maintain an original character. More detail is not automatically more honest when the detail is volatile, private or disconnected from a finished result.", "The opposite extreme is also weak: saying only that a tool was used gives the visitor no practical knowledge. FourFeetz avoids both ends by naming the production question, showing an actual frame or film where possible, describing the visible failure and explaining the acceptance or rejection decision."], bullets: ["Private: character master prompts and complete prompt chains", "Private: internal character bibles, weights and latest core settings", "Private: unreleased story and production assets", "Public: general planning, motion and review principles", "Public: selected real frames, finished films and honest limitations"] },
        { id: "what-worked", title: "What Worked: Share Decisions and Evidence", paragraphs: ["A visitor can learn to separate identity facts from shot facts, choose one action, protect the vertical safe area, inspect paws and accessories, compare edit joins and reject a structurally failed clip. None of those lessons requires the HARU master prompt. They are portable production principles that can be applied to an original character of the visitor’s own.", "FourFeetz supports an experience claim with a site asset: a published video, a character page, a production frame or a documented tool role. When a number, result or behind-the-scenes record is not available, we do not invent it. This keeps the studio record useful for viewers and defensible as the catalog grows."], table: { title: "The public/private boundary", headers: ["Material", "Status", "What visitors receive instead"], rows: [["Character master prompt", "Private", "Identity review criteria"], ["Internal character bible", "Private", "Public character page and selected references"], ["Latest core settings", "Private and changeable", "Tool role, limitation and visible result"], ["Finished films and shorts", "Public", "Direct playback and project records"], ["Production lessons", "Public", "Test, failure, working choice and takeaway"]] } },
        { id: "practical-takeaway", title: "Practical Takeaway: Protect the Recipe, Explain the Judgment", paragraphs: ["Creators can document their own work with the same boundary. Show the brief, approved public reference, failure category, revision decision and finished output. Keep any asset that would directly reproduce a protected character, unreleased story or current competitive workflow in the private production archive.", "For FourFeetz, this boundary helps manage original character IP and quality across HARU, OLI, MILO and the wider cast. Character pages establish the public identity, Videos show the released result, and Insights explain the transferable layer of the experience."], images: [{ src: "/images/characters/haru/portrait.png", alt: "Public portrait of HARU, the first original FourFeetz character", caption: "The public character page establishes HARU’s visible identity without exposing the studio’s complete character production package.", fit: "contain" }, { src: "/images/characters/oli/portrait.png", alt: "Public portrait of OLI, an original FourFeetz otter character", caption: "Different body types need different review priorities, while the internal character package remains protected.", fit: "contain" }] },
      ], faqs: [{ question: "Does FourFeetz share complete character prompts?", answer: "No. Character-specific master prompts, complete internal bibles and current core settings are proprietary production assets." }, { question: "What can visitors learn instead?", answer: "The site shares planning methods, visible review criteria, real production problems, selected frames, finished videos and practical acceptance decisions." }], related: [{ label: "About the Studio", title: "About FourFeetz Studios", href: "/about" }, { label: "Character Identity", title: "Meet HARU", href: "/characters/haru" }, { label: "Related Guide", title: "How HARU Was Created", href: "/insights/how-haru-was-created" }, { label: "Finished Work", title: "Watch FourFeetz Videos", href: "/videos" }],
    },
    ko: {
      ...koreanShared, slug: "what-we-keep-private-character-production", eyebrow: "FourFeetz 스튜디오 정책", title: "캐릭터 제작 과정에서 비공개로 관리하는 것", shortTitle: "캐릭터 제작에서 비공개로 관리하는 것", description: "FourFeetz가 캐릭터 마스터 프롬프트와 내부 제작 자산은 보호하면서 유용한 검토 원칙, 제작 근거와 완성 결과를 공개하는 이유입니다.", hero: "/images/insights/studio-workflow/private-character-studio-archive.png", heroAlt: "공개된 완성 작품과 닫힌 버건디·녹색 제작 폴더 영역을 나눈 월넛 스튜디오 아카이브", heroCaption: "공개 가능한 완성 결과는 보이게 두고 보호하는 제작 자산은 내용이 없는 닫힌 보관 폴더로 표현했으며 프롬프트, 설정이나 비공개 문서는 노출하지 않았습니다.", readTime: "약 7분", verdict: "FourFeetz는 배울 수 있는 제작 원칙과 독점적인 캐릭터 자산을 구분합니다. 방문자는 스튜디오의 캐릭터 IP를 유지하는 마스터 프롬프트나 내부 시스템 없이도 장면 정의, 정체성 검토와 완성 결과 판단을 배울 수 있습니다.", tags: ["캐릭터 IP", "제작 정책", "캐릭터 일관성", "스튜디오 운영"], keywords: ["비공개 AI 캐릭터 프롬프트", "캐릭터 IP 제작", "FourFeetz 캐릭터 자산", "책임 있는 제작 공유"], tools: [], characters: ["HARU", "OLI", "MILO"],
      sections: [
        { id: "what-we-tested", title: "실제로 확인한 것: 다른 제작자에게 실제로 도움이 되는 정보", paragraphs: ["완성 캐릭터 프롬프트가 가장 직접적인 교육 자료처럼 보일 수 있지만, 더 나은 제작 판단보다 보호된 디자인 하나를 재현하는 방법에 답합니다. FourFeetz는 대신 실제 First Shot, 완성 영상, 선별한 제작 프레임, 체크리스트와 구체적인 실패 설명을 공개합니다. 방문자는 장면에서 무엇을 지켜야 했고 무엇이 편집을 통과했는지 볼 수 있습니다.", "공개된 HARU 얼굴과 캐릭터 이미지는 실루엣, 나이, 털, 귀와 표정을 설명하는 시각적 사례로 사용합니다. 완전한 내부 캐릭터 바이블, 마스터 프롬프트, 가중치, 생성 이력이나 최신 설정은 포함하지 않습니다. 이 구분은 사이트를 유용하게 유지하면서 오리지널 캐릭터 정체성을 다운로드 가능한 조리법으로 만들지 않습니다."], images: [{ src: "/images/insights/haru-official-face-pack.png", alt: "귀, 눈, 주둥이와 강아지 비율이 일관된 공개 HARU 얼굴 참고", caption: "공개 HARU 레퍼런스로 검토 대상을 가르칠 수 있지만 완전한 내부 제작 체계는 비공개로 유지합니다.", fit: "contain", aspect: "landscape" }] },
        { id: "what-went-wrong", title: "문제가 되는 방식: 투명성과 전체 자산 공개를 혼동하기", paragraphs: ["모든 설정을 나열하면 도구, 모델과 화면이 바뀌기 때문에 거짓 확실성을 만들 수 있습니다. 오리지널 캐릭터를 유지하는 정확한 조합을 노출할 수도 있습니다. 정보가 변하기 쉽고 비공개이며 완성 결과와 연결되지 않았다면 세부사항이 많다고 더 정직한 것은 아닙니다.", "반대로 도구를 사용했다고만 말하면 실용적인 지식이 없습니다. FourFeetz는 제작 질문을 밝히고, 가능한 경우 실제 프레임이나 영상을 보여주며, 눈에 보이는 실패와 승인 또는 거절 판단을 설명해 두 극단을 피합니다."], bullets: ["비공개: 캐릭터 마스터 프롬프트와 전체 프롬프트 체인", "비공개: 내부 캐릭터 바이블, 가중치와 최신 핵심 설정", "비공개: 공개 전 이야기와 제작 자산", "공개: 일반적인 기획, 움직임과 검토 원칙", "공개: 선별한 실제 프레임, 완성 영상과 솔직한 한계"] },
        { id: "what-worked", title: "효과가 있었던 방법: 판단과 근거를 공유하기", paragraphs: ["방문자는 정체성 정보와 샷 정보를 구분하고, 한 가지 행동을 고르고, 세로 안전 영역을 보호하고, 발과 장식을 확인하며, 편집 접합부를 비교하고 구조적으로 실패한 클립을 거절하는 방법을 배울 수 있습니다. 이런 교훈에는 HARU 마스터 프롬프트가 필요하지 않으며 자신의 오리지널 캐릭터에 적용할 수 있습니다.", "FourFeetz는 경험을 말할 때 공개 영상, 캐릭터 페이지, 제작 프레임이나 기록된 도구 역할 같은 사이트 자산으로 뒷받침합니다. 수치, 결과나 비하인드 기록을 확인할 수 없을 때는 만들지 않습니다. 스튜디오 기록이 늘어나도 방문자에게 유용하고 검증 가능한 상태를 유지하는 방법입니다."], table: { title: "공개와 비공개의 경계", headers: ["자료", "상태", "대신 공개하는 것"], rows: [["캐릭터 마스터 프롬프트", "비공개", "정체성 검토 기준"], ["내부 캐릭터 바이블", "비공개", "공개 캐릭터 페이지와 선별 레퍼런스"], ["최신 핵심 설정", "비공개·변경 가능", "도구 역할, 한계와 눈에 보이는 결과"], ["완성 필름과 쇼츠", "공개", "직접 재생과 작품 기록"], ["제작 교훈", "공개", "테스트, 실패, 효과가 있던 선택과 핵심 정리"]] } },
        { id: "practical-takeaway", title: "실전 핵심 정리: 조리법은 보호하고 판단은 설명하기", paragraphs: ["자신의 작업도 같은 경계로 기록할 수 있습니다. 기획 의도, 승인된 공개 레퍼런스, 실패 유형, 수정 판단과 완성 결과를 보여주세요. 보호된 캐릭터, 공개 전 이야기나 현재 경쟁력 있는 제작 흐름을 직접 재현할 수 있는 자산은 비공개 제작 보관소에 두세요.", "FourFeetz에서는 이 경계가 HARU, OLI, MILO와 전체 캐릭터의 IP와 품질을 관리하는 데 도움이 됩니다. 캐릭터 페이지는 공개 정체성을 정하고, 영상은 공개 결과를 보여주며, 인사이트는 경험에서 옮겨갈 수 있는 원칙을 설명합니다."], images: [{ src: "/images/characters/haru/portrait.png", alt: "FourFeetz의 첫 오리지널 캐릭터 HARU 공개 초상", caption: "공개 캐릭터 페이지는 스튜디오의 전체 캐릭터 제작 패키지를 노출하지 않고 HARU의 시각적 정체성을 정합니다.", fit: "contain" }, { src: "/images/characters/oli/portrait.png", alt: "FourFeetz 오리지널 수달 캐릭터 OLI 공개 초상", caption: "서로 다른 체형에는 다른 검토 우선순위가 필요하지만 내부 캐릭터 패키지는 보호됩니다.", fit: "contain" }] },
      ], faqs: [{ question: "FourFeetz는 완성된 캐릭터 프롬프트를 공유하나요?", answer: "아니요. 캐릭터별 마스터 프롬프트, 완전한 내부 바이블과 현재 핵심 설정은 독점 제작 자산입니다." }, { question: "방문자는 대신 무엇을 배울 수 있나요?", answer: "기획 방법, 눈에 보이는 검토 기준, 실제 제작 문제, 선별 프레임, 완성 영상과 실용적인 승인 판단을 공개합니다." }], related: [{ label: "스튜디오 소개", title: "FourFeetz Studios 소개", href: "/ko/about" }, { label: "캐릭터 정체성", title: "HARU 만나기", href: "/ko/characters/haru" }, { label: "영문 가이드", title: "HARU 제작 과정", href: "/insights/how-haru-was-created" }, { label: "완성 작품", title: "FourFeetz 영상 보기", href: "/ko/videos" }],
    },
  },
};
